uploadNeuroDB/NeuroDB/Notify.pm

Modified the spool function in Notify.pm to use MySQL function NOW() Instead of UNIX_TIMESTAMP() for TimeSpooled column when inserting into notification_spool table. The reason is because the MySQL datatype of Timespooled column  is now changed from int to datetime.

Modification made to Notify.pm

---

imaging_install.sh

The following bug fixes/improvements  are made:
1) The Archive::Zip needs to be installed since it's used by the imaging uploader scripts
2) /data/incoming/ is created first as there maybe some cases where Site is not provided by the user
3) Added the missing dicom-archive in the path

Bug fixes and improvements

---

imaging_install.sh

This pull request contains the following:
- added the missing dicom-archive in the path
- created the /data/incoming/ parent directory first (before creating sub-directories)
- Installed Archive::Extract and Archive::Zip used  by NeuroDB/FileDecompress.pm
Note: For existing projects the perl libraries need to be installed manually as follows:
- sudo -S cpan install Archive::Extract;
- sudo -S cpan install Archive::Zip;

fixed bugs and added new features

---

uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

This pull request removes the -mri_upload_insert option from both tarchiveLoader and tarchive_validation.pl. And it automatically inserts into the mri_upload table (if not uploaded through front-end) or updates the mri_upload table with appropriate info otherwise.

Remove mri upload tag

---

README.md

Adding text to Loris-MRI Readme to clarify how, when, and which minc-tools and dctmk packages are installed for Ubuntu installations

Readme - details on Minc tools and Dicom toolkit installation

---

environment

Updating environment file template so that new imaging installations will have the correct setup
Correcting LORIS_CONFIG variable path to point to ..../dicom-archive/
so that the imaging pipeline's calls to LORIS_CONFIG/.loris_mri/prod will find it in the right place 
(issue since #56 )

correcting environment file : LORIS_CONFIG path 

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm

- Renamed to: IsCandidateInfoValidated
- Default value set to NULL instead of '0'
- To be used in conjunction with pull request: https://github.com/aces/Loris/pull/1501

IsValidated renamed in mri upload table 

---

README.md
imaging_install.sh
imaging_install_MacOSX.sh

No longer apt-get installing wrong MINC Toolkit.
Directing users to look at the BIC MINC site.
Misc toolkit clarifications.

Making MINC Toolkit check better + Clarifications on the toolkits

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm

Just added an "else" statement to the if condition that checks if the file is NOT dicom

Check patient name only if the file is DICOM, otherwise dcmdump crashes

---

DTIPrep/DTI/DTI.pm
DTIPrep/DTIPrepRegister.pl
DTIPrep/DTIPrep_pipeline.pl
MNI/FileUtilities.pm
auto/MNI/FileUtilities/check_output_dirs.al
auto/MNI/FileUtilities/check_output_path.al
imaging_install.sh
imaging_install_MacOSX.sh
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/cleanupTarchives.pl
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/register_processed_data.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl
uploadNeuroDB/upload

Since the MRI pipeline can now be run either from the command line or from the front-end (using the auto-launch), all data files/dirs have to be readable/writeable by user lorisadmin (command line) and www-data (front-end). Here's what I did to satisfy this requirement:
1. I modified the install script so that all files and directories under /data/$PROJ/data will be readable/writable by anyone who is a member of the Unix group lorisadmin. 
2. Any directory created by the MRI pipeline will have permission 770. 
3. User www-data should be part of the Unix group lorisadmin.
Caveat for existing projects:
Current projects should run these commands:
% sudo chgrp -R lorisadmin /data/$PROJ/data
% sudo chmod -R 2770 /data/$PROJ/data
% sudo chgrp -R lorisadmin /data/incoming
% sudo chmod -R 2770 …

Standardization of permissions for all MRI data files/dirs.

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/Notify.pm
uploadNeuroDB/imaging_upload_file.pl
uploadNeuroDB/imaging_upload_file_cronjob.pl
uploadNeuroDB/mass_jiv.pl
uploadNeuroDB/mass_nii.pl
uploadNeuroDB/mass_pic.pl
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

- notification_spool_table from MRIProcessingUtility.pm gets updated now with messages (the messages are similar to the messages in the log files), to be consistent with the ImagingUpload.pm
- printing messages to LOG files is still enabled for now
- printing messages on-screen only if $verbose option is set (when 'launching imaging_upload_file.pl' OR 'imaging_upload_file_cronjob.pl' with -verbose)
- Messages printed to LOG files and to notification_spool table  irrespective of the verbose option. Error messages print all the time, irrespective of verbose option as well. The notification_spool table now has a column with a verbose flag. This flag will be used by the Imaging Upoloader in the front-end to decide which messages are reported under the "Summary" or "Detailed" options
- In …

Enabled Notification Spool in MRIProcessingUtility.pm and Informative messages print only if $verbose option is set

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This PR corrects the flipping of the scenario (3) below (dcm2mnc will use -3 instead of 3.3), and should not impact scenarios (1) and (2):
1) When slice spacing (read form the DICOM header) is consistent with coordinate values (obtained from the XYZ position of each slice), this option should have no effect.
2) When the values are equal in magnitude and signs are opposite, dcm2mnc automatically uses                -usecoordinates option (this is a typical warning we get: 
WARNING: Coordinate spacing (-1) differs from DICOM slice spacing (1)
(perhaps you should consider the -usecoordinates option)
Using -1 for the slice spacing value
3) When values are different in magnitude and sign, then slice spacing is used BUT image will be flipped; 
a typical warning:
WARNING: Coordinate spacing (-3) …

Proposing -usecoordinates as the default option for dcm2mnc

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl

If the mri_protocol table checks pass, but the protocol is not registered in the prof file, the number of minc inserted in the mri_upload table was still incrementing.
An exit code is now used to track this and prevent incrementing the count for the number of minc files inserted.

Number of mincs inserted in the mri_upload could be wrong in some cases

---

uploadNeuroDB/NeuroDB/MRI.pm

If the mri_protocol table has more than one entry with a regex in the series_description column, all the files will be classified according to the scan type of the first entry in the mri_protocol table which has a regex entry. This pull request should fix this.

From Tom Beaudry: mri_protocol table checking when the row has a regex entry

---

uploadNeuroDB/imaging_upload_file.pl

- Added a message with the correct number of minc created and minc inserted into the database.
- A similar messaging clarification is done in the imaging_uploader in this Loris pull request:
https://github.com/aces/Loris/pull/1821
as per @nicolasbrossard feedback

More informative success message upon insertion scripts completion

---

README.md

Updating the Loris-MRI Readme for 16.0 : 
* Now recommending manual install of minc toolkit via Vlad's webpage on GitHub
* On certain /data/ mounts (especially Ubuntu) the mkdir commands fail when running the imaging_install.sh script.  User needs to manually run these commands afterwards.  This typically affects all the subdirectories under /data/$PROJ/data/ 
* Release version stated in the Readme
* Adding instruction to enable apache writability on data directories for Imaging Uploader

Readme updates for 16.0 (Loris-MRI Ubuntu Readme)

---

imaging_install.sh

Earlier releases had the $group statements already there, so I reverted back the changes that were removed in this pull request:
https://github.com/aces/Loris-MRI/pull/112/
and to it, I added the changes on the group ID to g+s from PR112, which is the proper thing to do.
This will also be clarified in the Readme file (https://github.com/aces/Loris-MRI/pull/123/files)

reverted the permissions on data directories from lorisadmin to apache

---

README.md

Since we're now on release branches, it's not enough to just clone the repo, which will get you the master branch.  
Users attempting to install Loris-MRI 16.0 must clone the v16.0.0 tag specifically.
Updated Readme to reflect this.
Also removed spurious minc path export instruction.

MRI Readme updates re environment, usergroups, version

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This change allows project to modify their prod files to use a different version of dcm2mnc and still use the same command format. For example dcm2mnc4ng does match the proper command string now.

new converter can use dcm2mnc command structure

---

batch_uploads_tarchive
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/tarchiveLoader

This is in reference to Redmine 6645.
The changes in this pull request is one way to get rid of the warnings (but the warnings are supposedly not harmful to keep; another recommended solution is to duplicate the entries with that warning; but I opted for option 1)

removed the used only once warning

---

batch_uploads_imageuploader
uploadNeuroDB/imaging_upload_file.pl

Run it as follows form where the Loris-MRI code base is:
$ ./batch_uploads_imageuploader -profile prod < imageuploader_list >log_batch_imageuploader.txt 2>&1
where imageuploader_list is a text file that has one scan details per line (example for 2 entries shown below); and each line (for each scan) consists of space delimited 1) the full path to the DICOM zipped scan, 2) Y or N depending on whether the scan is for a phantom or not, and 3) patient name following the PSCID_CandID_VisitLabel Loris convention for real candidates and left BLANK for phantoms 
An example of uploading 2 entries/scans to be uploaded:
/data/incoming/PSC0001_123457_V1.tar.gz  N  PSC0000_123456_V1
/data/incoming/Lego_Phantom_MNI_20140101.zip  Y

Batch upload of scans for projects not using the front-end imaging uploader

---

uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/tarchiveLoader

This proto function was moved out of tarchiveLoader and into MRI.pm because it will be used also in minc_insertion.pl
`uploadNeuroDB/tarchiveLoader -globLocation -profile prod ../../../../xxx_test/DCM_2016-02-17_ImagingUpload-11-34-xxxxxx.tar`

Move minc pics creation to MRI.pm

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/tarchive_validation.pl

Missing spaces and line breaks between two messages

Two minor formatting of error messages as they print

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl

This command will insert a violated scan since providing the acquisition protocol bypasses the protocol checks.  If you also need to bypass the extra_file_checks use bypass_extra_file_checks
Please note the -create_minc_pics option as well since it is usually created by the tarchiveloader script.
```
minc_insertion.pl -acquisition_protocol t2w -bypass_extra_file_checks -create_minc_pics -profile prod -globLocation -force  -tarchivePath /Users/xxxproject/dataTransfer/library/2009/DCM_2009-09-25_project_20110214_185904581.tar -mincPath /data/project/data/trashbin/TarLoad-3-34-pVzGC5/xxx0067_703739_v12_20090925_222403_18e1_mri.mnc
```

allow the insertion of violated scans

---

README.md
imaging_install.sh
imaging_install_MacOSX.sh

I think this is better than adding a note (as I did in this pull request: https://github.com/aces/Loris-MRI/pull/144) because:
1) We change group in the installation on subdirectories of /data/$PROJ/ , so we might as well do it in the installation script as well to be consistent (as opposed to adding a note, and do it on all subdirectories, not just some; more specifically the bin/mri/ path)
2) Most importantly, changes to the group ownership should happen on the prod file after its creation 
NOTE: The note I added in PR144 is more appropriate if I added it after point 4. or 5. (after having run .imaging_install.sh); but in all cases, it might be a good note to keep somewhere in the Wiki perhaps as a way of debugging permission-related errors
***
MAC install updates in this pull request …

Proper permission in installation2

---

uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/registerFile.pl
uploadNeuroDB/register_processed_data.pl

Related to Loris pull request: https://github.com/aces/Loris/pull/2189
This change adds to the files table an entry (claled ScannerCandID) with the candID from the mri_scanner table

Added a ScannerID column to files table: Redmine 10939

---

uploadNeuroDB/tarchive_validation.pl

To be in synch with determinePSC() and determineSubjectID()
which write to log in tarchive_validation and NOT in minc_insertion and tarchiveLoader. I think the same should apply to determineScannerID().

To_log set to 1 for determineScannerID

---

tools/BackPopulateSNRAndAcquisitionOrder.pl

Existing projects can now run this script (in the tools directory) to back-populate their existing database with SNR (in parameter_file table) and AcqOrderPerModality in files table.
This is in reference to these two pull requests:
https://github.com/aces/Loris-MRI/pull/142
and
https://github.com/aces/Loris-MRI/pull/160 
To be used AFTER this has been merged:
https://github.com/aces/Loris-MRI/pull/153
Run as follows in the /data/$PROJ/bin/mri/ directory:
tools/BackPopulateSNRAndAcquisitionOrder.pl -profile prod -tarchive_id 59 (for only this specific tarchive with tarchive_id = 59 in this example)
OR
tools/BackPopulateSNRAndAcquisitionOrder.pl -profile prod  (for all tarchives in the tarchive table)

Script to back-populate existing projects for SNR and AcqOrderPerModality

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This pull request re-computes the SNR basing it on setParameter() and getParameter() built-in functions... It also checks if the new SNR is different from the old/stored SNR (happening in the case where the noise_estimate algorithm from the MincToolKit is updated) and stores the new SNR value.
(The computeSNR() in the 16.1 branch could throw an exception (of duplicate entries; If the file already had an SNR entry, i.e. FileID, ParameterTypeID exists, and we re-run tarchiveLoader for example).

mysql error on duplicate entries

---

README.md
imaging_install.sh
imaging_install_MacOSX.sh

Updating version numbers, plus: 
Loris-MRI Readme updates: 
* more explicit mention for CentOS of how DICOM toolkit can be installed
imaging_install.sh:
* will no longer attempt to install (via apt-get) DICOM toolkit when run on CentOS
As a result, this script should no longer abort when trying to apt-get install the DICOM toolkit, leaving the user to manually execute the rest of the code.  For the first time, CentOS installs will actually run the last half of the script. 
Mac install script:  added a note that it's not supported

Readme and install script tweaks for 17.0

---

tools/seriesuid2fileid

This tool will help figure out if the dicom files you have are inserted in loris.  
Example of use:
`for i in $(find -type f); do dcmdump $i | grep SeriesInstanceUID; done | sort | uniq | cut -d "[" -f2 | cut -d "]" -f1 | /data/ibis/bin/mri/tools/seriesuid2fileid`

Command Line Tool to obtain FileID of inserted mincs using a lists of SeriesUID as STDIN

---

batch_uploads_imageuploader

This is to be in line with:
https://github.com/aces/Loris/pull/2100
in the Loris 16.1 release
Usage details are here:
https://github.com/aces/Loris-MRI/pull/133

Allowing a suffix at the end of filename in batch upload imageuploader, like is done in imaging uploader now

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm

As discussed in the imaging meeting, the user is now told what command to run to launch tarchiveLoader if the tarchiveID already exists (i.e. dicomTar.pl has completed).

When tarchiveID exists, instruct the user how to launch tarchiveLoader at the command line: Redmine 11157

---

uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

Session can be inactive, but should not be chosen for insertion

make sure the session is active

---

uploadNeuroDB/bin/mincpik

Removal of the deprecated array definition warning in mincpik: Redmine 11164

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_deletion.pl
uploadNeuroDB/tarchiveLoader

New script to delete minc file based on SeriesUID
`uploadNeuroDB/minc_deletion.pl -profile prod -seriesuid 1.3.12.2.1107.5.2.32.35045.201507232316035928639007.0.0.0 confirm`
```
./uploadNeuroDB/minc_deletion.pl -help                                                                                              
*******************************************************************************
Minc Deletion 
*******************************************************************************
Author  :   Gregory Luneau
Date    :   July 2016
Version :   1 revision  2
The program does the following:
Deletes minc files from the web interface by:
- Moving the existing files to an archive directory.
.mnc .jpg .header .raw_byte.gz
- Deleting all related data from 4 database tables.
parameter_file, …
```

remove minc, add a minc based on SeriesUID

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm

This will make the CandidateInfoValidation() ignore .DS_Store files which are commonly included with scans zipped on a MAC.
Subsequently, dicomTar.pl will remove this file (line 105 of: dicom-archive/dicomTar.pl)

Remove the .DS_Store file from the candidate info validation process

---

DTIPrep/DTIPrepRegister.pl
DTIPrep/DTIPrep_pipeline.pl
batch_uploads_imageuploader
batch_uploads_tarchive
database_files_update.pl
find_uploads_tarchive
imaging_install.sh
imaging_install_MacOSX.sh
tools/BackPopulateSNRAndAcquisitionOrder.pl
tools/ProdToConfig.pl
uploadNeuroDB/NeuroDB/DBI.pm
uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/cleanupTarchives.pl
uploadNeuroDB/mass_jiv.pl
uploadNeuroDB/mass_nii.pl
uploadNeuroDB/mass_pic.pl
uploadNeuroDB/minc_deletion.pl
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/registerFile.pl
uploadNeuroDB/register_processed_data.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

- Moving everything possible from the $profile file to the Configuration module (project-specific functions remain in the "prod" file)
- for existing projects: 
- a tool script (in `tools/ProdToConfig.pl`) is provided to help migrate the values from the $profile to the Config tables in the database, and can be invoked as follows:
from /data/$PROJECTI/bin/mri, run:
` tools/ProdToConfig.pl -profile prod`
- once the script is run successfully, projects are recommended to 1) make a backup of their original prod file, 2) cleanup/remove the entries that were migrated to the database from their $profile (essentially those that are in Section II), and 3) a) edit the function `get_DTI_Site_CandID_Visit` to become `get_DTI_CandID_Visit` (https://github.com/MounaSafiHarab/dicom-archive-tools/blob/744 …

Loris-MRI configurations moved to the front end from the $profile file: Redmine 8893

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm

Previous file_type content:
/tmp/ImagingUpload-12-48-Rv9qJY/LEGO_PHANTOM_HOS_20160830/DICOM/.test: ASCII text
New file_type content:
DICOM medical imaging data

[ImagingUpload.pm] Look inside file type and not file path for the word dicom

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm

If the patientname header in the DICOM files does not match the PSCID_CandID_VisitLabel naming convention (as entered using Imaging Uploader GUI), the error message stored in the notification_spool table (and also in the Log Viewer in the front-end) will show both the actual header info and what it is supposed/expected to be.
That was supposed to be informative for the user so they know how to fix the problem before the pipeline exits, however, if the site did not anonymize the PatientName, then our database is storing this info which it should not.
Simply remove the PatientName in the DICOM header from the stored message in the database.

Do not store PatientName header in notification_spool table:Redmine 13506

---

uploadNeuroDB/imaging_upload_file.pl

Currently running imaging_upload_file.pl to launch the pipeline expects 2 arguments:
upload_id and filepath
These should correspond to the same mri_upload entry. If they don't, the user doesn't really know what is being inserted: the file that corresponds to the upload_id or the upload_id that corresponds to the filepath!. It is actually the latter that happens (upload_id takes precedence).
An error should be thrown when inconsistent entries are provided to prompt the user to fix either/or of the entries.
p.s: one can argue that no need to require 2 arguments from the user; but this is apparently the case specifically for the user to confirm (twice) that it is this file/upload_id to be inserted.

Check consistent upload_id and filename when running the pipeline: Redmine 13507

---

dicom-archive/DICOM/DCMSUM.pm

If a scan for some reason does not contain a date of birth (for example when scanning a phantom), the dicom archive scripts would try to insert it as "". However, in MySQL 5.7, this creates an error and the tarchive entry is not created.
In order to fix this, reassigned date of birth and date of scan to undef if its value = ""

MySQL 5.7 - Mapping empty date of birth and scan to undef 

---

uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

Make sure to source the patch in [PR #3354](https://github.com/aces/Loris/pull/3354) to create and populate the column TarchiveID in the mri_protocol_violated_scans table.
Updates to the insertion scripts so that the new TarchiveID field of mri_protocol_violated_scans table can be populated when inserting a violated scan.
NOTE: this is for the next minor release of LORIS

Add TarchiveID to mri_protocol_violated_scans

---

uploadNeuroDB/NeuroDB/ImagingUpload.pm

The pipeline 1) gets the list of files from the unzipped uploaded file, then 2) removes the `__MACOSX` directory, and then 3) loops through the file list generated in step 1) and removes all those starting with a `.` (including the `.DS_Store` file).
a) The logic should be that we swap steps 1 and 2 so that the file list we are dealing with in the rest of the script excludes the `__MACOSX` directory and the files within.
b) Add line breaks after file/directory removal for user readability of the messages at the terminal (cleanup)

Get file list after removal of undesired directories like __MACOSX: Redmine 13508

---

docs/scripts_md/imaging_upload_file_cronjob.md
uploadNeuroDB/imaging_upload_file_cronjob.pl

pod2markdown uploadNeuroDB/imaging_upload_file_cronjob.pl > docs/scripts_md/imaging_upload_file_cronjob.md
User can type:
perldoc uploadNeuroDB/imaging_upload_file_cronjob.pl

[Documentation] imaging_upload_file_cronjob.pl

---

batch_uploads_tarchive
docs/scripts_md/batch_uploads_tarchive.md

Added perldoc for script `batch_uploads_tarchive`. Also ran `pod2markdown batch_uploads_tarchive` to generate `batch_uploads_tarchive.md`, the web-based documentation for the script.

[Documentation] - batch_uploads_tarchive

---

docs/scripts_md/File.md
uploadNeuroDB/NeuroDB/File.pm

Using perldoc/perlpod to document `File.pm` so that users can type in the terminal
`perldoc File.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `File.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown File.pm > File.md`

[Documentation] NeuroDB::File library perldocification

---

docs/scripts_md/FileDecompress.md
uploadNeuroDB/NeuroDB/FileDecompress.pm

Using perldoc/perlpod to document `FileDecompress.pm` so that users can type in the terminal
`perldoc FileDecompress.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `FileDecompress.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown FileDecompress.pm > FileDecompress.md`

[Documentation] NeuroDB::FileDecompress library perldocification

---

batch_uploads_imageuploader
docs/scripts_md/batch_image_uploader.md

pod2markdown batch_uploads_imageuploader > docs/scripts_md/batch_image_uploader.md
User can type:
perldoc batch_uploads_imageuploader

[Documentation] batch_upload_imageuploader

---

docs/scripts_md/BackPopulateSNRAndAcquisitionOrder.md
tools/BackPopulateSNRAndAcquisitionOrder.pl

pod2markdown tools/BackPopulateSNRAndAcquisitionOrder.pl > docs/scripts_md/BackPopulateSNRAndAcquisitionOrder.md
User can type:
perldoc tools/BackPopulateSNRAndAcquisitionOrder.pl 

[Documentation] BackPopulateSNRAndAcquisitionOrder.pl

---

docs/scripts_md/minc_deletion.md
uploadNeuroDB/minc_deletion.pl

pod2markdown uploadNeuroDB/minc_deletion.pl docs/scripts_md/minc_deletion.md
User can type:
perldoc uploadNeuroDB/minc_deletion.pl

[Documentation] minc_deletion.pl

---

docs/scripts_md/ImagingUpload.md
uploadNeuroDB/NeuroDB/ImagingUpload.pm

Using perldoc/perlpod to document `FileDecompress.pm` so that users can type in the terminal
`perldoc ImagingUpload.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `ImagingUpload.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown ImagingUpload.pm > ImagingUpload.md`

[Documentation] NeuroDB::ImagingUpload library perldocification

---

DTIPrep/DTI/DTI.pm

Since the ~~ operator is now deprecated in Perl, I refactored DTI.pm so it does its job without it. Basically, instead of trying to find a 'smart match' in the DTI_frames list, I use the == operator to find a strict _numerical_ match.

Refactor smart matching code in DTI.pm

---

docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/MRI.pm

Using perldoc/perlpod to document `MRI.pm` so that users can type in the terminal
`perldoc MRI.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `MRI.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown MRI.pm > MRI.md`

[Documentation] NeuroDB::MRI library perldocification

---

docs/scripts_md/Notify.md
uploadNeuroDB/NeuroDB/Notify.pm

Using perldoc/perlpod to document `Notify.pm` so that users can type in the terminal
`perldoc Notify.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `Notify.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown Notify.pm > Notify.md`

[Documentation] NeuroDB::Notification perldocification

---

uploadNeuroDB/minc_deletion.pl

Will update FileID fields to NULL in files_qcstatus and feedback_mri_comments before deleting a file in the files table if -deleteQCdata is set. Otherwise, the file won't be deleted due to the foreign key constraint to the files_qcstatus and feedback_mri_comments tables.
Note: this script needs a lot of clean up but this will be for another PR. It is quite messy and I am not 100% confident it might not screw up something in the database...

minc_deletion.pl - update QC tables before deleting files

---

docs/scripts_md/MRIProcessingUtility.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

Using perldoc/perlpod to document `MRIProcessingUtility.pm` so that users can type in the terminal
`perldoc MRIProcessingUtility.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `MRIProcessingUtility.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown MRIProcessingUtility.pm > MRIProcessingUtility.md`

[Documentation] NeuroDB::MRIProcessingUtility library perldocification

---

dicom-archive/DICOM/DCMSUM.pm
docs/scripts_md/DCMSUM.md

Using perldoc/perlpod to document `DCMSUM.pm` so that users can type in the terminal
`perldoc DCMSUM.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `DCMSUM.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown DCMSUM.pm > DCMSUM.md`

[Documentation] DICOM::DCMSUM library perldocification

---

docs/scripts_md/minc_insertion.md
uploadNeuroDB/minc_insertion.pl

Using perldoc/perlpod to document `minc_insertion.pl` so that users can type in the terminal
`perldoc minc_insertion.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `minc_insertion.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown minc_insertion.pl > minc_insertion.md`

[Documentation] minc_insertion.pl

---

docs/scripts_md/tarchive_validation.md
uploadNeuroDB/tarchive_validation.pl

Using perldoc/perlpod to document `tarchive_validation.pl` so that users can type in the terminal
`perldoc tarchive_validation.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `tarchive_validation.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown tarchive_validation.pl > tarchive_validation.md`
Dependencies added: perldoc, Pod::Markdown

[Documentation] tarchive_validation.pl perldocification

---

docs/scripts_md/mass_pic.md
uploadNeuroDB/mass_pic.pl

Using perldoc/perlpod to document `mass_pic.pl` so that users can type in the terminal
`perldoc mass_pic.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `mass_pic.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown mass_pic.pl > mass_pic.md`

[Documentation] mass_pic.pl perldocification

---

README.md
imaging_install.sh

On the MRI side, since the user provides the projectname during the interactive install; it is better to auto-populate/change the default values that LORIS sets.
It is already done for some setting (Imaging Pipeline section), but makes sense to do it also for the Path section in the configuration module.

Installer: Populate the default LORIS config settings for the MRI paths (Redmine 13915)

---

docs/scripts_md/mass_nii.md
uploadNeuroDB/mass_nii.pl

Using perldoc/perlpod to document `mass_nii.pl` so that users can type in the terminal
`perldoc mass_nii.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `mass_nii.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown mass_nii.pl > mass_nii.md`
Dependencies added: perldoc, Pod::Markdown

[Documentation] mass_nii.pl perldocification

---

docs/scripts_md/tarchiveLoader.md
uploadNeuroDB/tarchiveLoader

arguments were added in this pull request https://github.com/aces/Loris-MRI/pull/246; need to be removed (check minc_insertion.pl and tarchvive_validation.pl; none has the arguments in their logHeader() function).

[documentation] Fix tarchiveLoader after it was perlified

---

uploadNeuroDB/NeuroDB/File.pm

In this PR, instead of hardcoding the different file types in the File.pm file, reads this information from the ImagingFileType table.
The only exception left in the if statements are if a file matches '.mnc' or '.mnc.gz', it will determine the file type to be 'mnc'.
Redmine ticket associated with this PR: https://redmine.cbrain.mcgill.ca/issues/13839

Grep the different file types from the DB instead of hardcoding it in the code

---

tools/BackPopulateSNRAndAcquisitionOrder.pl
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

Add an `-upload_id` option that can be used to call the `minc_insertion.pl` script. Will keep the `-tarchivePath` option as well.
Running minc_insertion.pl now requires that either `-tarchivePath` or `-upload_id` options are set (but not both at the same time). 
=> If `-tarchivePath` is given, the corresponding `UploadID` is fetched at the beginning of the script. The `UploadID` is then passed to the different functions of `MRIProcessingUtility.pm` for logging purposes instead of querying the `UploadID` based on the `-tarchivePath` in each function.
With this change, no dependant anymore on the tarchive location for logging purposes.
Linked Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/13936

Adding -uploadID option to minc_insertion.pl

---

docs/scripts_md/database_files_update.md
tools/database_files_update.pl
tools/update_to_relative_path/database_files_update.pl

First, moved this script under the tools directory as it is an (old) tool scripts.
Second, using perldoc/perlpod to document `database_files_update.pl` so that users can type in the terminal
`perldoc database_files_update.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `database_files_update.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown database_files_update.pl > database_files_update.md`
Dependencies added: perldoc, Pod::Markdown

[Documentation] database_files_update.pl perldocification 

---

docs/scripts_md/MakeArchiveLocationRelative.md
tools/MakeArchiveLocationRelative.pl
tools/update_to_relative_path/MakeArchiveLocationRelative.pl

First, moved this script under the tools directory as it is an (old) tool scripts.
Second, using perldoc/perlpod to document `MakeArchiveLocationRelative.pl` so that users can type in the terminal
`perldoc MakeArchiveLocationRelative.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `MakeArchiveLocationRelative.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown MakeArchiveLocationRelative.pl > MakeArchiveLocationRelative.md`
Dependencies added: perldoc, Pod::Markdown

[Documentation] MakeArchiveLocationRelative.pl perldocification

---

uploadNeuroDB/NeuroDB/ExitCodes.pm
uploadNeuroDB/minc_insertion.pl

This PR adds validation to the arguments passed on the command line and also gets rid of some warnings that were popping up when I tested this script. It also makes sure that the `globArchiveLocation` option behaves like it should by correcting the MySQL statement used to fetch a `tarchive` based on its `ArchiveSource`'s base name

Improve minc_insertion.pl command line validation

---

uploadNeuroDB/NeuroDB/ExitCodes.pm
uploadNeuroDB/bin/concat_mri.pl
uploadNeuroDB/bin/minc2jiv.pl

- concat_mri.pl
- minc2jiv.pl
- no exits are present in Mincinfo_wrapper
- did not do mincpik as its future might be compromised once we discuss PR #288. Can always do it later on.
Link to redmine ticket: https://redmine.cbrain.mcgill.ca/issues/14054

Adding exit codes to uploadNeuroDB/bin scripts

---

tools/BackPopulateSNRAndAcquisitionOrder.pl
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/UnexpectedValueException.pm
uploadNeuroDB/NeuroDB/objectBroker/MriScanTypeOB.pm
uploadNeuroDB/mass_pic.pl
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/register_processed_data.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

This is the refactoring of methods scan_type_text_to_id and scan_type_id_to_text of MRI.pm to make them use the new Database.pm module. All modules/scripts that use these methods either directly or indirectly have also been refactored.

Refactored methods scan_type_text_to_id and scan_type_id_to_text of MRI.pm

---

DTIPrep/DTIPrepRegister.pl
DTIPrep/DTIPrep_pipeline.pl
batch_uploads_imageuploader
batch_uploads_tarchive
dicom-archive/DICOM/DCMSUM.pm
dicom-archive/dicomTar.pl
dicom-archive/updateMRI_Upload.pl
docs/scripts_md/ExitCodes.md
uploadNeuroDB/NeuroDB/ExitCodes.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/bin/minc2jiv.pl
uploadNeuroDB/imaging_upload_file.pl
uploadNeuroDB/minc_deletion.pl
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/register_processed_data.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

As @nicolasbrossard pointed out in PR #289, the exit codes are limited to the range 0-255. If a value outside that range is used as an exit code, it is truncated to 8 bits.
In order to refactor this, the follow google doc has been created to map the old and new exit codes:
https://docs.google.com/spreadsheets/d/1QsDQl9rXvut6Li62Rba7iUFRBT8mq6bDfX9JjYRsVQY/edit#gid=0
NOTE: since the exit codes were not yet part of any release, it is the perfect time to refactor them within the upcoming release of 19.1.
Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/14247

ExitCodes refactoring so that their number fit in the range 0-255

---

DTIPrep/DTIPrepRegister.pl
docs/scripts_md/DTIPrepRegister.md

Using perldoc/perlpod to document `DTIPrepRegister.pl` so that users can type in the terminal
`perldoc DTIPrepRegister.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `DTIPrepRegister.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown DTIPrepRegister.pl > DTIPrepRegister.md`

[Documentation] DTIPrepRegister.pl perldocification

---

DTIPrep/DTIPrep_pipeline.pl
docs/scripts_md/DTIPrep_pipeline.md

Using perldoc/perlpod to document `DTIPrep_pipeline.pl` so that users can type in the terminal
`perldoc DTIPrep_pipeline.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `DTIPrep_pipeline.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown DTIPrep_pipeline.pl > DTIPrep_pipeline.md`

[Documentation] DTIPrep_pipeline.pl perldocification

---

DTIPrep/DTI/DTI.pm
docs/scripts_md/DTI.md

Using perldoc/perlpod to document `DTI.pm` so that users can type in the terminal
`perldoc DTI.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `DTI.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown DTI.pm > DTI.md`

[Documentation] DTI::DTI library perldocification

---

dicom-archive/DICOM/Private.pm
docs/scripts_md/Private.md

Using perldoc/perlpod to document `Private.pm` so that users can type in the terminal
`perldoc Private.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `Private.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown Private.pm > Private.md`

[Documentation] DICOM::Private library perldocification

---

dicom-archive/DICOM/Fields.pm
docs/scripts_md/Fields.md

Using perldoc/perlpod to document `Fields.pm` so that users can type in the terminal
`perldoc Fields.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `Fields.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown Fields.pm > Fields.md`

[Documentation] DICOM::Fields library perldocification

---

dicom-archive/DICOM/VRfields.pm
docs/scripts_md/VRfields.md

Using perldoc/perlpod to document `VRfields.pm` so that users can type in the terminal
`perldoc VRfields.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `VRfields.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown VRfields.pm > VRfields.md`

[Documentation] DICOM::VRfields library perldocification

---

dicom-archive/DICOM/Element.pm
docs/scripts_md/Element.md

Using perldoc/perlpod to document `Element.pm` so that users can type in the terminal
`perldoc Element.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `Element.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown Element.pm > Element.md`

[Documentation] DICOM::Element library perldocification

---

dicom-archive/DICOM/DICOM.pm
docs/scripts_md/DICOM.md

Using perldoc/perlpod to document `DICOM.pm` so that users can type in the terminal
`perldoc DICOM.pm` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `DICOM.md` file has been created so that we have a web displayed version of the documentation.
`pod2markdown DICOM.pm > DICOM.md`

[Documentation] DICOM::DICOM library perldocification

---

docs/scripts_md/register_processed_data.md
uploadNeuroDB/register_processed_data.pl

Using perldoc/perlpod to document `register_processed_data.pl` so that users can type in the terminal
`perldoc register_processed_data.pl` and get the documentation.
Using the `pod2markdown` tool from perl `Pod::Markdown` module, the `register_processed_data.pl` file has been created so that we have a web displayed version of the documentation.
`pod2markdown register_processed_data.pl > register_processed_data.md`

[Documentation] register_processed_data.pl perldocification

---

uploadNeuroDB/minc_deletion.pl

Fixes a simple bug that was inserted when doing the perl documentation.
Who wants to review it? Should be the easiest review ever ;).

Fix a bug that was inserted in minc_deletion when writing the perl documentation

---

DTIPrep/DTIPrepRegister.pl
DTIPrep/DTIPrep_pipeline.pl

DTIPrepRegister.pl and DTIPrep_pipeline.pl crashes when there is a trailing / in the data_dir variable set in the Config module. This PR removes the trailing / when it exists from the data_dir variable.
Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/14351

Removing trailing / of data_dir in DTIPrep_pipeline and DTIPrepRegister scripts

---

dicom-archive/updateMRI_Upload.pl
uploadNeuroDB/NeuroDB/Database.pm
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm
uploadNeuroDB/NeuroDB/objectBroker/MriScanTypeOB.pm
uploadNeuroDB/NeuroDB/objectBroker/MriUploadOB.pm
uploadNeuroDB/NeuroDB/objectBroker/TarchiveOB.pm

When a `SELECT` statement is executed with the new database framework, a reference to an array of hash references is returned. The key/value pairs of this hash are the column names (as specified in the `SELECT` statement) and their values. This consequently modifies the behaviour of all object brokers. 
Basically, in the past you had code like:
```perl
$r = $objectBroker->get( ['col1', 'col4', 'col12'], { col2 => 'nbro', col7 => 5 });
$col12ForFourthRecord = $r->[3]->[2];   
```    
Whereas now, you would see:
```perl
$r = $objectBroker->get( ['col1', 'col4', 'col12'], { col2 => 'nbro', col7 => 5 });
$col12ForFourthRecord = $r->[3]->{'col12'};   
```

Select statements in the new database framework now return a reference to an array of hash references.

---

uploadNeuroDB/minc_insertion.pl

This fixes the call to the `validateCandidate` function from the `MRIProcessingUtility.pm` file to have only one parameter (as it should have been since tarchive source location is not an argument of the function. 
Tested on a scan and it works as expected.
@MounaSafiHarab was not sure if this should go to 19.2. I think we can easily change the branch if we decide to merge it for 20.0 instead.

Fixing minc_insertion.pl call to validateCandidate, had too many parameters

---

docs/scripts_md/MRIProcessingUtility.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/tarchiveLoader

follow up to PR #283
@llevitis PR in LORIS (https://github.com/aces/Loris/pull/3523) had 2 tables, so the MRI counterpart should ensure projects no longer have comma separated values in BOTH those tables. So add the `mri_protocol_checks` here besides the check in PR#283 for `mri_protocol`.

Exit if comma separated values in mri_protocol checks ValidRange column

---

uploadNeuroDB/NeuroDB/DBI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/tarchiveLoader

Basically redoing #264 after catastrophic rebasing. Only took 3 hours of my time today...
Until now, the exclusion of localizers were hardcoded in the tarchiveLoader in the variable $exclude.
This PR allows the possibility to configure the sequences that a user might want to exclude from the dcm2mnc command (localizers, scouts and other). In the "Imaging Pipeline" section of the Config module, it is now possible to specify the different series descriptions to be excluded from the insertion pipeline. Two default example have been set in LORIS: is `localizer` and `scout` (see screenshot below)
The imaging script will then used the values stored in the Config modules for the `excluded_series_description` config setting and create a regular expression out of those values to use afterwards …

MRI exclusion scans such as localizers read from the Config module. 

---

Mincinfo_wrapper
concat_mri.pl
environment
minc2jiv.pl
mincpik

Copy of PR #288 but rebased for 20.0 if time to test and merge it before the release. Leaving #288 open in the meantime but labeled as blocked.
Instead of having links in the main directory to the scripts stored in uploadNeuroDB/bin, add the path to uploadNeuroDB/bin in the environment file.
Need to add in your environment file the following path to the export PATH line:
/data/%PROJECT%/bin/mri/uploadNeuroDB/bin
where %PROJECT% should be replaced by the name of your project

Remove links to scripts for 20.0

---

uploadNeuroDB/tarchiveLoader

This is in reference to a comment made by @MounaSafiHarab on PR #321 where missing a `\n` at the end of a `print` statement in the `tarchiveLoader`

Fixed missing \n at the end of a print statement

---

uploadNeuroDB/tarchiveLoader

A warning would be printed by `tarchiveLoader` if it tries to update a record in table `mri_upload` for which `number_of_mincInserted` is `NULL`. Variable `$oldCount` is undefined in this case. This PR sets `$oldCount` to `0` in this situation so it is always defined.

Fixed a statement in tarchiveLoader that would cause a PERL warning in specific circumstances.

---

docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/register_processed_data.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

This pull request removes the unused PendingStaging field from the files table as was discussed during the LORIS imaging meeting of February 2nd, 2018.
See also:
- associated redmine ticket: https://redmine.cbrain.mcgill.ca/issues/13876
- associate PR on the LORIS side: https://github.com/aces/Loris/pull/3569
Note for reviewers: 
I removed all the code associated to this PendingStaging field. I checked IBIS and PREVENT-AD, this field is always filled with 0. Maybe you could check your DB just to be sure but at this point, I am fairly confident this is not used.

Removing PendingStaging field from the files table

---

imaging_install.sh
imaging_install_MacOSX.sh

Removal of the creation of `sites` directory in the `incoming` folder since they are not used anymore by the pipeline.
See also: Redmine https://redmine.cbrain.mcgill.ca/issues/14967

Removing creation of site incoming directory from the install scripts

---

dicom-archive/profileTemplate
docs/scripts_md/GetRole.md
docs/scripts_md/InsertRole.md
docs/scripts_md/MRI.md
docs/scripts_md/MriScannerOB.md
docs/scripts_md/ObjectBroker.md
docs/scripts_md/PSCOB.md
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/GetRole.pm
uploadNeuroDB/NeuroDB/objectBroker/InsertRole.pm
uploadNeuroDB/NeuroDB/objectBroker/MriScannerOB.pm
uploadNeuroDB/NeuroDB/objectBroker/ObjectBroker.pm
uploadNeuroDB/NeuroDB/objectBroker/PSCOB.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/register_processed_data.pl
uploadNeuroDB/tarchiveLoader

This adds object brokers for tables `mri_scanner` and `psc`. In doing so, it uses two new Moose features: inheritance and roles. This allows simplification of the object broker classes. The existing object broker classes will eventually be converted using this new model in a future PR. 
How/what to test:
- Thorough testing of the `minc_insertion.pl` , `tarchiveLoader` and `register_processed_data.pl` scripts. Try to build test cases that specifically validate the modified code.
- Build a test script that creates one or both of the object brokers, perform various select/insert operations and make sure that they work. The synopsis of both object brokers can be helpful for that task.

Added object brokers for tables mri_scanner and psc.

---

batch_uploads_tarchive.pl
dicom-archive/updateMRI_Upload.pl
load_tarchive_db.sh
tools/BackPopulateSNRAndAcquisitionOrder.pl
tools/seriesuid2fileid.pl
uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/imaging_upload_file_cronjob.pl
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/tarchiveLoader.pl
uploadNeuroDB/tarchive_validation.pl

- tools/seriesuid2fileid
- uploadNeuroDB/tarchiveLoader
- uploadNeuroDB/NeuroDB/ImagingUpload.pm
- uploadNeuroDB/imaging_upload_file_cronjob.pl
- load_tarchive_db.sh
- find_uploads_tarchive
- batch_uploads_tarchive
1. **batch_uploads_tarchive**: should be run with the -profile option set:
`batch_uploads_tarchive -profile prod < tarchive_list.txt`
2. **tools/seriesuid2fileid**: should be run with the -profile option set:
`seriesuid2fileid -profile prod < seriesuid_list.txt`
- load_tarchive_db.sh appears to be an old and outdated script, only tested that the addition of the option <profile> worked, which it did
- redmine ticket associated with this PR: https://redmine.cbrain.mcgill.ca/issues/5975

Removing hardcoded "prod" from imaging scripts

---

docs/scripts_md/MRI.md
docs/scripts_md/create_nifti_bval_bvec.md
tools/create_nifti_bval_bvec.pl
uploadNeuroDB/NeuroDB/MRI.pm

For DWI files, the binary `mnc2nii` is not creating the `.bvec` and `.bval` files necessary to obtain the direction informations. Added support in the imaging pipeline so that those files can be created automatically within the function `make_nii` of the `MRI.pm` file.
- if there are values in the MINC header `acquisition:bvalues` then create the `.bval` file using these values
- if there are values in the MINC headers `acquisition:direction_x`, `acquisition:direction_y` and `acquisition:direction_z` then create the `.bvec` file using these values 
A script has been created in the `tools` directory to create the missing bval/bvec files for projects that have the 'create_nii' configuration set to 'Yes'. This script is called `create_nifti_bval_bvec.pl`.
Simply run `mnc2nii`, then call the …

Added creation of bvec and bval files when creating NIfTI files

---

dicom-archive/profileTemplate
docs/02-Install.md
docs/scripts_md/File.md
uploadNeuroDB/NeuroDB/File.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/register_processed_data.pl

This PR moves the `filterParameters()` function out of the `profileTemplate` file to the `File.pm` library.
On April 6th, 2018, an email was sent to all LORIS-MRI users to ask whether any project had customized that function in their profile file. As of May 31st, no project has mentioned that they customized that function so it should be safe to go ahead and move that function back into the LORIS-MRI code.
**See Redmine ticket**: https://redmine.cbrain.mcgill.ca/issues/13934
**Note for testers**: I tested changing the length in the filterParameters function that I moved to File.pm to 10 and it decreased the amount of entries in parameter_file, ergo, it works as expected. I then put back that value to 1000 as originally specified in the profileTemplate

Moving the filterParameters() function out of the profileTemplate file

---

DTIPrep/DTI/DTI.pm
DTIPrep/DTIPrepRegister.pl
docs/scripts_md/DTI.md
docs/scripts_md/MRI.md
docs/scripts_md/register_processed_data.md
tools/MakeNiiFilesBIDSCompliant.pl
uploadNeuroDB/NeuroDB/File.pm
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/register_processed_data.pl

This PR cleans up the multiple functions to grep MINC header information and merges them into a single function in `MRI.pm`.
See also: https://redmine.cbrain.mcgill.ca/issues/15106
To test:

Cleanup multiple ways of getting header info from MINC

---

docs/scripts_md/updateHeaders.md
tools/mass_perldoc_md_creation.pl
tools/updateHeaders.pl

Fixes a bug where the DICOM archive were updated on the filesystem but not in the database, hence modifying the md5sum of the DICOM archive and corrupting the entry in the `tarchive` table.
It also documents the script using Perldoc and added the script to `mass_perldoc_md_creation.pl`.

Fixed updateHeaders.pl that did not run dicomTar.pl properly when -database option was set

---

dicom-archive/profileTemplate
docs/02-Install.md
docs/scripts_md/MRIProcessingUtility.md
tools/BackPopulateSNRAndAcquisitionOrder.pl
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/tarchiveLoader

Moves the function `getSNRModalities()` out of the profile file. The list of modalities to compute SNR on will now be stored in the Config module of LORIS under the Imaging Pipeline Section as shown in the screenshot below:
The function `computeSNR()` of `MRIProcessingUtility.pm` has been updated to grep that information from the Config module now instead of the profile file.
SQL for this changes are in https://github.com/aces/Loris/pull/4159
Make sure you have run the patch from this LORIS PR (https://github.com/aces/Loris/pull/4159; link to be updated to final URL of the patch at the time of release documentation) and that you have updated the Config module with the modalities listed in the function `getSNRModalities` of your profile file.
From now on, the insertion scripts will rely on …

Move getSNRModalities() out of the profile file (prod file)

---

dicom-archive/get_dicom_info.pl

This PR modifies the behaviour of script `get_dicom_info.pl`: DICOM files passed as arguments to this script are now reported as not being DICOM only if they __don't__ have header `(0020,0032)` __and__ `-slicepos` was passed on the command line.
`dcmodify -e` can be useful during testing if one wants to remove header `(0020,0032)` from an existing DICOM file.
This fixes [issue #364](https://github.com/aces/Loris-MRI/issues/364)

Header (0020,0032) now only checked when -slicepos is passed on the command line

---

batch_uploads_imageuploader
dicom-archive/updateMRI_Upload.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

Title says it all. This PR implements the right way to get the effective UID in a Perl process. To test, simply verify that the variable containing the user ID is set correctly in the modified scripts.
This fixes [Redmine ticket 14115](https://redmine.cbrain.mcgill.ca/issues/14115).

Use getpwuid instead of a call to whoami to get the userid throughout the MRI pipeline codebase.

---

dicom-archive/DICOM/DCMSUM.pm
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/tarchive_validation.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/tarchive_validation.pl

This pull request goes with the LORIS changes to the renaming of the following fields:
- `tarchive` table: `PatientGender` renamed to `PatientSex`
- `candidate` table: `Gender` renamed to `Sex`
- make sure to source the patch from the LORIS PR that changes the field names
- try inserting a scan that will create a candidate and insert into the tarchive table
PR on the LORIS side: https://github.com/aces/Loris/pull/3897/files

Replace the "Gender" field with "Sex" in the candidate and tarchive tables 

---

DTIPrep/DTI/DTI.pm

When a project uses NIfTI files creation, the DTIPrep pipeline breaks when searching for a t1 in the native subdirectory as it returns the NIfTI file instead of the MINC file. This fixes the issue and returns only the MINC file.
-[x] issue #352

Fix DTIPrep pipeline when create NIfTI is set to yes

---

python/lib/physiological.py
uploadNeuroDB/NeuroDB/File.pm

This fixes an issue raised in https://github.com/aces/Loris/pull/3695#discussion_r242642123 where entries into the `parameter_type` table created by the imaging script were not linked to a parameter type category via `parameter_type_category_rel`. The code in this PR fixes this issue.
The imaging part if corrected in the `File.pm` file and the electrophysiology part is corrected in `physiological.py` library. 
Make sure to source the SQL patch in the following LORIS PR https://github.com/aces/Loris/pull/4263 to fix existing projects' table.

[Bug fix] Insert into parameter_type_category_rel table when creating new parameter_type

---

dicom-archive/get_dicom_info.pl
docs/scripts_md/ImagingUpload.md
docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

The `dcm2mnc` conversion is currently failing on datasets that contains Siemens reports. This PR adds a check in `get_dicom_info.pl` so that the script skips the scanner report.
Also added a check so that only DICOM medical imaging data files are passed to `get_dicom_info.pl` when converting data to MINC files.

[Bug fix] fix get_dicom_info.pl so that it skips the scanner reports

---

docs/scripts_md/get_dicom_files.md
tools/get_dicom_files.pl

Tiny change to the documentation: mentioned that the directory argument to `-d` has to exist or an error is raised.

Updated documentation of get_dicom_files.pl.

---

README.md

This PR fixes an issue with the install process of the EEG pipeline documented in the README.md. Added `sudo apt-get install libmysqlclient-dev` as a dependency.

[EEG install] fix README.md dependencies for EEG pipeline

---

python/lib/candidate.py
python/lib/physiological.py

A new BIDS EEG dataset was provided and tested against the current insertion pipeline and a few little bugs needed to be fixed:
- `Gender` was not populated in the `candidate` table
- Date of birth was not properly parse and populated in the `candidate` table
- The `Unit` field of `physiological_channel` was not populated when a unit was provided in the BIDS structure (typo in the BIDS field name) 
**This should be part of release 20.2 since it is the release that some of our collaborator will be using to insert EEG data and those bugs were found when testing their dataset**

[EEG bug fixes] Fixing a few bugs discovered when inserting a new BIDS EEG dataset

---

uploadNeuroDB/NeuroDB/MRI.pm

This PR fixes a bug introduced in the code when modifying `get_dicom_info.pl` behaviour and the logic of determining if a DICOM file is indeed of type DICOM medical imaging file. The linux command `ls @files_list | xargs file` failed on larger DICOM datasets due to the amount of DICOM files given as an argument in a single line. To fix this, the list of files is now written in a temporary file on which the command `cat` is called, listing one file per line instead:
`cat $tmp_file | xargs files`
Run a large DICOM study through the imaging pipeline (before the PR, it would have failed, after the PR it works). Note that in my case, the DICOM study contained only 1290 files.

[Bug fix] Fix get dicom info bug for long list of DICOM files

---

tools/example_scripts/deletemincsqlwrapper.pl
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This PR rename the CenterID field column of the candidate table to RegistrationCenterID, which will correspond to the CenterID at which the candidate was first registered. This should never be changed for a given candidate. 
https://github.com/aces/Loris/pull/4078

Rename candidate CenterID to RegistrationCenterID

---

python/lib/candidate.py
python/lib/database.py

This PR fixes the BIDS import script and rename the `candidate` table field `Gender` to `Sex` as this field was renamed in major and the BIDS import scripts were part of the latest minor release (20.2.0). 
Note that the code changes on the MRI side was already done to account for the change of field name in the database (see #336).
[x] issue #380

Replace Gender by Sex in bids insertion scripts

---

tools/MakeNiiFilesBIDSCompliant.pl

The MRI BIDS dataset created using the tool `MakeNiiFilesBIDSCompliant.pl ` fails the BIDS validator due to the SliceTiming field being export in milliseconds instead of seconds. This PR converts the BIDS SliceTiming field into seconds so that it can pass the BIDS validator.

Convert slice timing to seconds when creating the BIDS MRI structure

---

batch_uploads_tarchive
uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/tarchiveLoader
uploadNeuroDB/tarchive_validation.pl

Modifies the update and select queries on `mri_upload` to use the `UploadID` instead of the `TarchiveID` to avoid updating multiple entries in the `mri_upload` table when more than one `UploadID` refers to the same `TarchiveID`.

Use UploadID to update mri_upload instead of TarchiveID

---

README.md
docs/scripts_md/run_defacing_script.md
environment
tools/run_defacing_script.pl
uploadNeuroDB/NeuroDB/File.pm
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/bin/deface_minipipe.pl

This PR adds a new tool that will allow defacing of the structural images listed in the Config module under the imaging pipeline section in the new field called `modalities_to_deface` (See PR https://github.com/aces/Loris/pull/4232 on the LORIS side for the SQL patch).
Note that the script `deface_minipipe.pl` in `uploadNeuroDB/bin` has been taken out of the BIC EZminc GitHub repo (https://github.com/BIC-MNI/EZminc/tree/ITK4/scripts).
Screenshot of a defaced scan:
1) Make sure to populate the configuration `modalities_to_deface` in the imaging pipeline section of the Configuration module with all scan types that you wish to deface (typically, T1W, T2W, T2*, FLAIR and other 3D structural images)
2) To run the tool, go to the `tools` directory and run:
```perl run_defacing_script.pl …
```

Addition of a LORIS tool to deface  structural images and register the defaced images back into LORIS

---

dicom-archive/DICOM/DCMSUM.pm
dicom-archive/dicomTar.pl
docs/scripts_md/DCMSUM.md
uploadNeuroDB/NeuroDB/ImagingUpload.pm

This removes the default `-clobber`  behaviour when calling `dicomTar.pl` in `ImagingUpload.pm` to avoid creating many issues in the database as raised in [this presentation](https://docs.google.com/presentation/d/1BpAvGcduTESUcDNrSyZOiz8sszbweJ7H_slKZfM-6so/edit#slide=id.g4e9a10fecf_0_151.).
In addition, a check has been added at the top of the script to stop `dicomTar.pl` if the study has already been uploaded and the option `-clobber` has not been used.

Remove default -clobber option when calling dicomTar.pl

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/tarchiveLoader

In the context of open science, no dates are available with the dataset therefore, the following needed to be fixed:
- the DICOM archives cannot be moved to a year subfolder when running `tarchiveLoader`. If no acquisition date is available, the DICOM archive will remain in the `tarchive` directory and will not be moved to a subdirectory. If the acquisition date is present in the DICOM, then the behaviour remains the same.
- the call to `Mincinfo_wrapper` in the function `get_mincs` of `MRIProcessingUtility.pm` includes the `-date` option and then sorts based on the date. However, sorting the files based on the date does not really sort the files since they are all acquired on the same date for most of them. Therefore, if we wish to sort the files based on their order of acquisition, we …

Fixed the pipeline for when there is no date in the DICOM files

---

imaging_install.sh
python/lib/physiological.py
uploadNeuroDB/NeuroDB/File.pm

This PR cleans up all the different paths that are referring to the same path (a.k.a. `/data/%PROJECT%/data/`). This gets rid of the Config settings `mincPath`, `imagePath` and `data` and updates the code accordingly.
The code changes on the LORISI front can be found in https://github.com/aces/Loris/pull/4314
Make sure that your Config setting `dataDirBasepath` is configured to the proper data path (typically `/data/%PROJECT%/data`)

Removed imagePath, mincPath and data from imaging_install.sh 

---

docs/02-Install.md
docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

Rebased Mouna's PR and added support for the MIN/MAX values in the `mri_protocol_checks` table.
The `mri_protocol` and `mri_protocol_checks` tables have been normalized to replace all `%_range` fields by `%_min` and `%_max` values (see aces/Loris#3973). 
- if for a given parameter (*e.g.* TR) a `*Min` **AND** a `*Max` value have
been specified, then it will check if the parameter of the scan falls into the
range \[Min-Max].
- if for a given parameter, a `*Min` is provided but not a `*Max` then the
imaging pipeline will check if the parameter of the scan falls is higher than
the `*Min` value specifie in the table.
- if for a given parameter, a `*Max` is provided but not a `*Min` then the
imaging pipeline will check if the parameter of the scan falls is lower than
the `*Max` value specified …

Change hyphen separated ranges in mri_protocol to MIN/MAX columns: Redmine 14022 

---

uploadNeuroDB/bin/bestlinreg_claude.pl
uploadNeuroDB/bin/deface_minipipe.pl

The current defacing algorithm failed on about 4% of the sessions due to a failed linear registration step. However, a newer and greater the `bestlinreg.pl` from the MINC tool has been improved but is not yet part of the MINC tool release. Therefore, in this PR:
- the newest and greatest linear registration tool (`bestlinreg_claude.pl`) was added in the `uploadNeuroDB/bin` directory of LORIS-MRI
- the call to perform linear registration was modified in `deface_minipipe.pl` to call this newest and greatest tool (`bestlinreg_claude.pl`)
Note that with this new linear registration tool, there is a 100% success rate of the defacing pipeline so far.
- an issue discovered when defacing the PREVENT-AD dataset that might happen for other projects as well.

Improvement of the success rate of the defacing pipeline

---

batch_uploads_imageuploader

`batch_uploads_imageuploader` creates a duplicate entry in the `mri_upload` table when loading one upload:
```
+----------+-------------+---------------------+---------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------+------------------------+-----------------------+------------+-----------+--------------------------+---------------------+-----------+------------------------------------------+-----------+
| UploadID | UploadedBy  | UploadDate          | UploadLocation                                                                        | DecompressedLocation                                                                 | InsertionComplete | …
```

fix batch_uploads_imageuploader that inserted duplicated uploads

---

docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/MRI.pm

This PR contains the code changes needed to add the `image_type` check in the `mri_protocol` and `mri_protocol_violated_scans`. 
This `image_type` header field is a key variable as this is the only MINC header that allows to differentiate between a fieldmap phase difference from a fieldmap magnitude file which have different purposes when it comes to analyses and the insertion pipeline should be able to recognize one from the other. This is also the case for MP2RAGE modalities and other modern imaging modalities, hence the need to add that field in the mri_protocol table.
Example:
- image_type for fieldmap phase difference image: `ORIGINAL\\PRIMARY\\P\\ND` (P for phase)
- image_type for fieldmap magnitude image: `ORIGINAL\\PRIMARY\\M\\ND` (M for magnitude)
Note that because of the …

Adding the image_type to the mri_protocol when identifying for imaging protocol

---

docs/scripts_md/batch_run_defacing_script.md
tools/batch_run_defacing_script.pl
tools/mass_perldoc_md_creation.pl

Added a tool script in order to be able to run the defacing pipeline in parallel on multiple CPUs using QSUB.
This script runs the defacing pipeline on multiple sessions. The list of session IDs are provided through a text file (e.g. C<list_of_session_IDs.txt> with one sessionID per line).
An example of what a C<list_of_session_IDs.txt> might contain for 3 session IDs to be defaced:
```
123
124
125
```
- no issue reported but this script was particularly useful in speeding the mass defacing on an open dataset so making it available to the LORIS-MRI community :)

Added a batch script to run the defacing in parallel on multiple CPUs using QSUB

---

docs/scripts_md/batch_run_pipeline_qc_face_script.md
tools/batch_run_pipeline_qc_face_script.pl
tools/mass_perldoc_md_creation.pl
uploadNeuroDB/bin/pipeline_qc_face.pl

This PR includes a modified version of the MINC tool `pipeline_qc_face.pl` to work with the LORIS-MRI pipelines in `uploadNeuroDB/bin` and a tool script that allows running `pipeline_qc_face.pl` in parallel on multiple CPUs.
Those new tools will create a 3D rendering of the face to ensure that the defacing went properly. They will produce jpeg files in a directory specified using the `-out_basedir` option of `batch_run_pipeline_qc_face_script.pl` that can be looked at to make sur the face was properly scrubbed. 
- no issue reported but this script was particularly useful in creating the QC images for open science :)

Add a tool to produce 3D rendering of the face for visual QC of the defaced images

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This PR fixes a bug found when testing 21.0 when selecting entries in `mri_acquisition_dates`.

Fix a bug when running query on mri_acquisition_dates

---

uploadNeuroDB/NeuroDB/MRI.pm

The call to `registerScanner` in `MRI.pm` got screwed up when resolving conflicts between minor and major. This PR fixes the issue.

Correct bug to call to registerScanner

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This PR resolves the warning message below that appeared when computing SNR on a dataset for the first time:
`Use of uninitialized value  in string ne at /data/demo/bin/mri/uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm line 1892.`

Gets rid of the warning message Use of uninitialized value when computing SNR

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

The following warning message gets displayed when the pipeline run on a dataset with a valid acquisition date:
`Argument 2016-08-15 isn't numeric in numeric eq (==) at /data/demo/bin/mri/uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm line 974.`
This PR resolves this warning message that got introduced by https://github.com/aces/Loris-MRI/pull/395.

Fixes a warning message of non-numeric value in comparison

---

environment

The order in the environment file had to be changed in order for new projects to be able to use the `deface_minipipe.pl` from LORIS-MRI instead of the one from the MINC tools. 
For existing projects, instructions were given at the time of release [20.3.0](https://github.com/aces/Loris-MRI/releases/tag/v20.3.0) on how to modify their environment files in the section **Notes for existing projects**.

Reorder environment file for new installs

---

docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/MRI.pm

The `in_range` logic was not properly set and led to wrong identification of the MRI protocol and mislabelled scans... 
This PR fixes this bug found while testing 21.0.

Fix in_range logic

---

docs/scripts_md/MRIProcessingUtility.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/tarchiveLoader.pl

This PR removes the function that was added in `MRIProcessingUtility.pm` when the `mri_protocol` table was modified to remove the `,` in the range columns. This function is not needed anymore now that the range columns have been split into `Min` `Max` columns.

Remove deprecated function isValidMRIProtocol now that the mri_protocol contains MIN MAX values

---

docs/04-Scripts.md

Modified the documentation to add a section about the deletion script and to point to the MD file documentation on how to run the script.

Add a note about the deletion script in the docs of LORIS-MRI

---

imaging_install.sh

The `DBI.pm` library is missing in the CPAN install instructions run by the install script. This PR adds it to the install script to correct this mistake.

[install script] Add the missing DBI.pm library to the CPAN install

---

python/bids_import.py
python/lib/candidate.py

That change has been made on the perl scripts (#341) but apparently was not integrated into the python script for insertion of BIDS datasets. This fixes this.

[BIDS EEG import] Changed the field CenterID to be RegistrationCenterID when querying the candidate table

---

python/lib/eeg.py

This fixes one last occurence of CenterID that should have been renamed to RegistrationCenterID in #442.

[BIDS EEG import] Missed one renaming the CenterID field of the candidate table in one occurence in python scripts

---

python/lib/eeg.py

This is fixing an if statement to check if `acq_time` is available in `sub-XX_scans.tsv` before using the value of that field into a variable.
Fixes error message when `acq_time` not present in that `.tsv` file:
```
File "/data/qpn/bin/mri/python/lib/eeg.py", line 407, in fetch_and_insert_eeg_file
eeg_acq_time = entry['acq_time']
KeyError: 'acq_time'
```

[BIDS EEG] Fixing an if statement to check if `acq_time` is available in `sub-XX_scans.tsv`

---

python/lib/eeg.py
python/lib/scanstsv.py

If the age at the time of acquisition can be parsed in the BIDS `sub-XXX_scans.tsv` file, then the `age_at_scan` will be inserted into the `physiological_parameter_file` table.
In addition, added the copy of the `sub-XXX_scans.tsv` file into the LORIS BIDS import directory.
Finally, refactored the way the `sub-XXX_scans.tsv` file is read so it can be extended to other modalities following the BIDS structure. A new library called `lib/scanstsv.py` was created to deal with that file.
This fixes the age import for the Cuban EEG dataset which will be using 21.0.

[BIDS EEG] Get age at scan from sub-XXX_scans.tsv file of the BIDS structure

---

python/lib/bids.json
python/lib/bidsreader.py
python/lib/eeg.py

The release of pybids 0.7 was a major release for them with major change in their layout and it broke the python LORIS-MRI BIDS insertion scripts...
In this PR, the code of the BIDS insertion pipeline has been updated to use the latest stable release of pybids (a.k.a. 0.9.1).
This fixes #389.
Make sure to update your pybids package to 0.9.1:
```
pip uninstall pybids
pip install --upgrade pip
pip install pybids==0.9.1
```

[BIDS EEG] Upgrade code so can be used with pybids 0.9.1

---

uploadNeuroDB/NeuroDB/MRI.pm

`MRI.pm` was still using the 2-argument version of `MRIScannerOB`'s `get` function, which is the old way of using this object broker. I switched it to the single argument (correct) version.
Fixes #460

Fixed incorrect use of MRIScannerOB in MRI.pm.

---

uploadNeuroDB/NeuroDB/File.pm

Until now, the whole header of a MINC file was dumped into a row of `parameter_file`, taking a lot of space in the database and the SQL dump created for that table.
During the imaging meeting of July 4th, a decision has been made to no longer store that row to gain some space in the database, hence, removing it from the imaging pipeline code.
This is linked to the LORIS PR https://github.com/aces/Loris/pull/4925
Try inserting a MINC file into the database and make sure the `header` row is not present in the `parameter_file` table after insertion

[Clean up] the full MINC header entry will not be imported into the parameter_file table anymore

---

docs/04-Scripts.md
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/minc_deletion.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_deletion.pl

The associated PR https://github.com/aces/Loris/pull/4962 on the LORIS side removes the `mri_acquisition_dates` table from the database as this table does not necessarily store the correct acquisition date. Instead, replaced all the queries to look for the minimal date present in the `parameter_file` table which is more robust than what was stored in mri_acquisition_dates.
Note: the decision to remove this table was taken during an imaging meeting in 2017 and confirmed at an other imaging meeting in 2019.
https://redmine.cbrain.mcgill.ca/issues/6040

[SQL] Removed insertion or updates in mri_acquisition_dates

---

tools/get_dicom_files.pl

get_dicom_script does not handle series descriptions that contain either a `&` or `\` well. Care must be taken when specifying the `--transform` option to `tar` with such series (see changes).
To test, one can "fake" a series description that contains one of the special characters and check that the script completes successfully. 
This fixes issue #433

get_dicom_file fails when the series description contains a sed special character.

---

dicom-archive/dicomTar.pl

As the title says. The calls to the various system funtions that are made (`hostname`, `gethostbyname`, `inet_ntoa`) can all either return `undef` or `croak` under rare circumstances. The code in dicomTar should always check the return value of these calls and never assume that they are always successful.
Tip to test: you can cut and paste the small chunk of code that computes the value of `$hostname` into a small program and run it on your VM. To have full control over what the system functions return, you can override them, like so:
```perl
*{hostname} = sub {
croak "Hostname call failed";
};
*{gethostbyname} = sub {
return undef;
};
```
Fix for https://redmine.cbrain.mcgill.ca/issues/13517

Bulletproof the way the host's IP address is computed in dicomTar.pl.

---

uploadNeuroDB/mass_nii.pl

when `-minFileID` is provided, instead of looking for FileID higher than the min FileID provided, it was looking for smaller FileIDs... This PR fixes the issue in `mass_nii.pl`.

[mass_nii.pl] Fix the query logic

---

dicom-archive/DICOM/DCMSUM.pm
dicom-archive/dicomTar.pl

`dicomTar.pl` continues executing insertion into the tarchive tables even if one insertion failed. In this PR, we catch the insertion failure and return the error so `dicomTar.pl` can be stopped and further insertions prevented.
Needed to modified the database function of `DCMSUM.pm` to return the error when an SQL insertion failed during the execution of `dicomTar.pl`.
Note: ideally, the returned error message would be inserted in the `notification_spool` table which should be a separate PR.
https://redmine.cbrain.mcgill.ca/issues/13841

[dicomTar.pl] Exit when insertion or update fails

---

tools/gzip_nifti_files.pl
uploadNeuroDB/NeuroDB/MRI.pm

NIfTI files created by `mnc2nii` are uncompressed files taking a lot of disk space. However, most softwares using NIfTI files are supporting the compressed version of NIfTI (`.nii.gz`). 
In this PR, the created NIfTI files are automatically gzipped during the creation of NIfTI files and a tool script has been created to be able to gzip all NIfTI files already present in the database if one wants to gzip every single NIfTI files.
No issue opened but needed to save disk space on a LORIS project (before gzipping 2.3TB of disk space was used, after gzipping 714GB of space was used).
Note: if a NIfTI file is not present on the filesystem for whichever reason, the tool script will issue a warning and go to the next NIfTI file.

Gzip NIfTI files to save disk space

---

README.md
imaging_install.sh
imaging_install_MacOSX.sh

PR #334 removed the creation of subdirectories in the `/data/incoming` directory but the question about the list of sites to provide at the time of install was not removed.
This PR updates the install instruction from the install scripts (Linux and Mac OS) and the `README.md` to remove that question when running the install script since the variable `site` is not used anywhere in the script.

[Install] Removed the site question from the install script

---

batch_uploads_imageuploader.pl
batch_uploads_tarchive.pl
docs/scripts_md/ConfigOB.md
tools/batch_run_defacing_script.pl
tools/batch_run_pipeline_qc_face_script.pl
tools/create_nifti_bval_bvec.pl
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm
uploadNeuroDB/mass_pic.pl
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/register_processed_data.pl

In this PR, all boolean Config options are queried using the `ConfigOB` instead of the function in `DBI.pm`.

[Moose] ConfigOB - grepping the boolean config settings using ConfigOB

---

docs/01-Introduction.md
docs/02-Install.md
imaging_install.sh
python/bids_import.py
python/lib/bidsreader.py
python/lib/imaging.py
python/lib/mri.py
python/lib/scanstsv.py
python/lib/utilities.py

This allows the import of MRI datasets already organized according to the BIDS standards. The following BIDS modalities/entities are supported on the MRI side:
`anat`, `func`, `dwi`, `fmap`
More modalities will come when they will officially be released in the BIDS standards.
**Note:** if a BIDS imaging scan type (aka, the BIDS suffix which is the last part of the filename like `T1w`, `T2w`, `dwi`, `FLAIR`...) is not found in the `mri_scan_type` table, the BIDS insertion script will insert a new scan type in that table so it can be used to insert the file.
#451 
New dependencies were added to be able to create a pic of the NIfTI files imported via the BIDS structure. To install those dependencies, make sure to first source the LORIS-MRI python virtual environment (`source …

[BIDS import] Included the import of MRI datasets organized as BIDS studies

---

uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm

The function `getCreateCandidates` of the config object broker was not looking for the right config setting.

Fixes the OB to grep the config setting createCandidate

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

In the `validateCandidate` function of the library `MRIProcessingUtility.pm`,  the check to see if it is a phantom scan happens to low in the function so when checking the patient name of a phantom scan, there is always an MRICandidateError logged and returned for phantom scan.
In this PR, the check is moved at the beginning of the function so that no further candidate validation is performed on a phantom scan.
- a bug found when upgrading CCNA to 21.0

[bug fix] Fixes bug encountered when validating candidate for phantoms

---

uploadNeuroDB/tarchive_validation.pl

In `tarchive_validation.pl`, the extraction of the tarchive is done to call a function that does not exist and have not existed for years. This removes the unnecessary additional extraction that contributes to slowing the insertion pipeline.
Notes for imaging meeting:
- even if `dicomFilter` was filtering the DICOM, it would not update the `tarchive` so it would just be doing it with no follow up
- no studies are using such a function in their `prod` file (CCNA, IBIS, PREVENT-AD, QPN, myelineurogene...)
Should be safe to remove but will discuss at the next imaging meeting just in case.

remove unnecessary extra extraction from tarchive_validation.pl

---

python/lib/imaging.py
python/lib/mri.py
python/lib/physiological.py

This fixes a bug during the file type determination in the python scripts. Instead of looking for the file type string in the whole file path, it now uses a regex to properly match the extension as it should have been done from the beginning...
Use the code from this branch on the cuban dataset that Iris has.

[BIDS EEG import bug fix] This fixes a bug happening during the file type determination

---

dicom-archive/profileTemplate.pl

Both CCNA and IBIS set an `isPhantom` key in the `getSubjectIDs` function of the config file to specify if the scan is a phantom based on the PatientName. [The code refers to that key](https://github.com/aces/Loris-MRI/blob/b38e7c0af96a541632e3bdad14d9f1083daee43e/uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm#L1789) when checking if a scan is a phantom or an actual candidate session. The `profileTemplate.pl` was not updated with these changes unfortunately so this PR takes care of it.
Also removed the `isPhantom` function of the config file as it is not used anywhere in the scripts.
Make sure to update your config file with those changes if it was not done already.

[config update] profileTemplate cleanup

---

python/lib/physiological.py

The BIDS events.tsv header names for physiological files have changed from `events_value` to `value` and `event_sample` to `sample` according to the latest BIDS release. This PRs implements the new header names and supports both conventions.

[python] fixed the wait the value was encoded in the events file for electrophysiology datasets

---

docs/scripts_md/delete_imaging_upload.md
tools/delete_imaging_upload.pl

Addition of a new option to `delete_imaging_upload.pl`: `-file basename`, which allows the deletion of a file with a specific base name. The file must meet one of these criteria:
1. Listed in table `file` and is directly produced by the MRI pipeline (as in `TarchiveSource != NULL`).
2. Listed in 'files` but has been produced/computed using another file directly produced by the pipeline (i.e referenced in `files_intermediary`).
3. Listed in `parameter_file` and is associated to parameter `check_pic_filename`, `check_nii_filename`, `check_bval_filename` or `check_bvec_filename`.
Note that if a file is deleted, all the files that were produced using it are also deleted.

Allow deletion of a file with a specific base name in delete_imaging_upload.pl

---

docs/scripts_md/MRI.md
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/minc_insertion.md
docs/scripts_md/tarchiveLoader.md
docs/scripts_md/tarchive_validation.md
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/tarchiveLoader.pl
uploadNeuroDB/tarchive_validation.pl

These changes removes the option `-new_scanner` from the pipeline scripts since by default all projects register new scanners when they are not already present in the `mri_scanner` table.
#526

Remove new_scanner option from the pipeline

---

DTIPrep/DB
batch_uploads_tarchive.pl
dicom-archive/dicomTar.pl
dicom-archive/updateMRI_Upload.pl
docs/04-Scripts.md
docs/scripts_md/ImagingUpload.md
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/MriUploadOB.md
docs/scripts_md/TarchiveOB.md
docs/scripts_md/batch_uploads_tarchive.md
docs/scripts_md/dicomTar.md
docs/scripts_md/minc_insertion.md
docs/scripts_md/tarchiveLoader.md
docs/scripts_md/tarchive_validation.md
docs/scripts_md/updateMRI_Upload.md
uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/MriUploadOB.pm
uploadNeuroDB/NeuroDB/objectBroker/TarchiveOB.pm
uploadNeuroDB/minc_insertion.pl
uploadNeuroDB/tarchiveLoader.pl
uploadNeuroDB/tarchive_validation.pl

These changes removes the option `-globLocation` from the pipeline scripts since now the `archiveLocation` is always a relative path, hence our scripts are always being used with the `-globLocation` turned on. This gets rid of the option and keep the behaviour in the pipeline as if the option was always given (a.k.a. querying the `tarchive` table with ` WHERE ArchiveLocation LIKE basename($tarchive)`
#527 
Ensure to remove the `-globLocation` option from any call to the scripts that used to have that option in your own scripts or cron jobs.

Remove -globLocation option

---

dicom-archive/updateMRI_Upload.pl
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/TarchiveOB.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/MriUploadOB.pm
uploadNeuroDB/NeuroDB/objectBroker/TarchiveOB.pm
uploadNeuroDB/minc_insertion.pl

Code that searches for either an archive with a specific basename or an MRI upload ties to an archive with a specific basename should be refactored to use either the `TarchiveOB` or `MriUploadOB`. 
Fixes #531

Use TarchiveOB and MriUploadOB through the entire LORIS-MRI codebase.

---

INSTALL.Mac.md
dicom-archive/dicomTar.pl
uploadNeuroDB/NeuroDB/ImagingUpload.pm

Fixed several errors that occurs when running the imaging pipeline on a Mac sandbox, including some Mac install updates. 
Note, the changes made do not change the behaviour of the pipeline on a Linux computer.

[bug_fix] Fix pipelines errors when running the pipeline on a Mac OS X sandbox

---

dicom-archive/dicomTar.pl

Fixed the invalid find command in script `dicomTar.pl` that fails to delete files with name `__MACOSX`.

Fixed invalid find command in dicomTar.pl.

---

uploadNeuroDB/minc_insertion.pl

When the pipeline tries to create a visit to insert a scan and cannot do so because either the project ID or subproject ID in the `prod` file are invalid, there should be an entry in table `notification_spool` indicating so.
1. Edit your `prod` file and make sure that `createVisitLabel` is set to 1. 
2. In your `prod` file, Specify a `SubprojectID` that does not exist for your project
3. Try to insert a scan for a candidate/visit such that there are no entries in table `session` for that candidate/visit.
Ensure that once the pipeline finishes, there is a notification in table `notification_spool` stating that the projectID/subprojectID specifications are invalid and the session could not be created.
Fixes #541

Missing notifications when the pipeline cannot create a visit.

---

python/mass_electrophysiology_chunking.py

Running `mass_electrophysiology_chinking.py` script led to the following error:
```
Traceback (most recent call last):
File "mass_electrophysiology_chunking.py", line 168, in <module>
main()
File "mass_electrophysiology_chunking.py", line 69, in main
make_chunks(smallest_id, config_file, verbose)
File "mass_electrophysiology_chunking.py", line 163, in make_chunks
print('Chunking physiological file ID ' + physiological_file_id)
TypeError: can only concatenate str (not "int") to str
```
This PR fixes the print statement and convert to string the `PhysiologicalFileID` value before printing it.

[python] fix mass electrophysiology chunking script

---

python/lib/imaging.py

The timestamp was not being populated upon insertion into the `parameter_file` table. This fixes the issue.

[python] fix timestamp not being populated in the parameter_file

---

uploadNeuroDB/minc_insertion.pl

As the title says. Reasons with newlines have been found to cause problems in the MRI Violations module on the LORIS side. See https://github.com/aces/Loris/issues/6366
https://github.com/aces/Loris/pull/6366
Note: although these PRs are related, they can be merged separately.

Ensure Reason column of table MRICandidateErrors does not contain newlines

---

tools/MakeArchiveLocationRelative.pl

During the refactoring of the config table SQL call, a typo was inserted in `MakeArchiveLocationRelative.pl` rendering the script to not run properly as instead of getting the `tarchiveLibraryDir`, the script fetched `dataDir` config setting.

[bug fix] Fixes a bug in MakeArchiveLocationRelative.pl

---

python/lib/bidsreader.py

There is a bug in the current code for the BIDS import script that does not allow sessions to import all modalities when session have different modalities.
Example of a dataset with different modalities per visits:
```
sub-01
|__ ses-01
|__ func
|__ fmap
|__ ses-02
|__ func
|__ fmap
|__ ses-03
|__ anat
```
In the case of such a dataset, only `anat` modalities would be inserted before the bug fix (the content of the latest visit)...
This PR fixes this bug and allows for the insertion of all modalities into the database even when sessions do not have the same modalities.

[python] fix bug when visits have different modalities

---

INSTALL.Mac.md
README.md
docs/02-Install.md
docs/AppendixA-Troubleshooting_guideline.md

This gets rid of references to the `master` branch from the LORIS-MRI documentations and uses the new defaults `main` branch instead.
The README instruction was also modified in favour of installing releases instead of cloning `master` as users should use official releases instead of the development branch. This mimics the behaviour from the LORIS repo.

Get rid of master references in the docs to use the main branch instead

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This modifies the pipeline to include the insertion of the acquisition date information in the new `AcquisitionDate` field of the `files` table that is introduced by https://github.com/aces/Loris/pull/6892.
Reasons for adding this field in the files table are summarized in https://github.com/aces/Loris/issues/6883.
See #553 for the LORIS-MRI issue.

Populate the added AcquisitionDate field in the files table

---

python/bids_import.py
python/lib/database.py
python/lib/eeg.py
python/lib/imaging.py
python/lib/mri.py
python/mass_electrophysiology_chunking.py
python/mass_nifti_pic.py

This refactors the old python scripts to use the `python/lib/database_lib/config.py` library to query the `Config` table.
https://github.com/aces/Loris-MRI/issues/523

[python] Refactor the script to use the Config class when querying the config table

---

imaging_install.sh

Script `imaging_install.sh` fails on CentOS. The script uses Unix command `lsb_release` in an attempt to find what OS the user is using but this command does not exist on CentOS...This PR uses a more reliable way to determine the system's OS.
Although not directly related to this PR, I also updated the install wiki for CentOS: https://github.com/aces/Loris/wiki/CentOS-Imaging-installation-transcript. The updates mentions two additional Python libraries that need to be installed for `imaging_install.sh` to work on CentOS. When testing that the new `imaging_install.sh` script in this PR, be sure to follow the **new** CentOS install instructions.

Fixed script imaging_install.sh that fails on CentOS.

---

dicom-archive/dicomTar.pl
uploadNeuroDB/NeuroDB/ImagingUpload.pm

Was getting this error when trying to insert a scan:
```
find \/data\/not_backed_up\/ImagingUpload\-17\-45\-h4XhVY -name '__MACOSX' -delete  
find: cannot delete ‘/data/not_backed_up/ImagingUpload-17-45-h4XhVY/__MACOSX’: Directory not empty
```

[23.0.0][Bugfix] Fixing error for deleting __MACOSX folder

---

python/lib/candidate.py

L106 is using sys without importing it, causing a python error.

Missing import fix

---

dicom-archive/DICOM/DCMSUM.pm

Was having issues with inserting an image for DTI_TENSOR that had no values for EchoTime, RepTime and SliceThickness. 
This fix generalizes that any series type with empty values for those fields should be replaced by `undef`.

[22.0][Bugfix] Undef EchoTime, RepTime and SliceThickness

---

docs/scripts_md/delete_imaging_upload.md
tools/delete_imaging_upload.pl

This PR improves the validation done on the `upload_ID` argument of script `delete_imaging_upload.pl`. It will determine the `tarchive` associated to the uploads whose IDs are passed on the command line and check that *only* these uploads are associated to that archive and no other. An error message is issued if that is not the case. For example, say uploads `U1` and `U2` are tied to archive `A`. An attempt to delete only `U1` will fail: both `U1` and `U2` have to be deleted in the same command.
Resolves #559

Implement strict checks for command line arguments of delete_imaging_upload.pl.

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This is a fix for the bug that was reported by Alfredo on the LORIS mailing list. See issue #564 for details.

Circumvent a dcm2mnc bug that causes modalities to be ignored in specific occasions.

---

python/lib/mri.py

This PR fix issue #577
In importing bids dataset, scan.json is wrongly parsed instead of scan.tsv
The solution has been consulted with @cmadjar , who provided input and shares the credit.
Please assign @cmadjar as one reviewer.
cc:
@gdevenyi

fix scan.json wrongly taken instead of scan.tsv

---

docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/minc_insertion.pl

As the tile says. The bug was due to a missing argument when calling function `MRI::make_pics`
Fixes #576

minc_insertion.pl crashes when used with option -create_minc_pics.

---

python/mass_nifti_pic.py

When using a file ID range with the `mass_nifti_pic.py` script, the image associated to the last (max) file ID is not generated. This PR corrects this.
Fixes #583

mass_nifti_pic.py does not handle file ID ranges well.

---

uploadNeuroDB/imaging_non_minc_insertion.pl

This bug was due to the fact that when the acquisition date is inserted in table `parameter_file`, the name of the parameter used is incorrect. This PR changes it to the correct value.
Fixes #572.

Fixed wrong parameter name for scan acquisition date in imaging_non_minc_insertion.pl

---

docs/scripts_md/MRIProcessingUtility.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl

This PR removes warnings that were issued when script `minc_insertion.pl` was run with option `bypass_extra_file_checks`. 
Fixes #575.

Remove warnings in minc_insertion scripts when -bypass_extra_file_checks is used

---

batch_uploads_imageuploader.pl

Fix the warning 
```
Use of uninitialized value $_ in pattern match (m//) at ./batch_uploads_imageuploader.pl line 165.
```
in batch_uploads_imageuploader.pl

Fix uninitialized value warning in batch_uploads_imageuploader.pl

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

When the Config setting `createCandidates` is set to Yes, the pipeline always go into the `CreateMRICandidates` function of `MRIProcessingUtility.pm` and returns the following error:
```
Spool message is: ERROR: Cannot create candidate (MTL0001, 123456) as a candidate with PSCID=MTL0001 already exists
```
This adds an if statement before calling the function `CreateMRICandidates` to check first if a candidate with the PSCID already exists. If it exists, the call to the function `CreateMRICandidates` will be skipped.
NOTES: this bug fix does not apply to 23.0 since the code to determine candidate information has been revamped and is working well.

Fix create candidate bug in 22.0.0 when Config createCandidate is set to yes

---

python/lib/scanstsv.py

This PR fix issue #586
In importing bids dataset, scantsv.py is not able get acquisition time for mri.
The cause is that self.tsv_entries is a list of dict rather than a dict.
The solution: 
if it is a list, then
filtered out the unrelated dict objects for the current acquisition_file, and handle error in case of more than one entry exist. Then go from there.
cc:
@gdevenyi

fix bids import acquisition time error

---

uploadNeuroDB/NeuroDB/MRI.pm

When the MRI pipeline performs a check on each file in an archive to see if it is a DICOM file, it first builds the list of files in the archive and writes it an a temporary file. The problem is that the path of this temporary file is always the same, irrespective of the MRI pipeline process that writes/uses it. Consequently, it can contain files that belong to multiple MRI pipeline processes if two or more are running concurrently.
Fixes #594

Fix bug occurring when multiple MRI pipeline processes are running simultaneously

---

tools/delete_imaging_upload.pl

The current version of the imaging upload delete script cannot create backups of the database information deleted unless the  MySQL user used when running the script has the `PROCESS` privilege. This is due to the fact that the script uses `mysqldump` to back up the information it deletes and table spaces are backed up by default. But the delete script does not need to back up table spaces, so option `--no-tablespaces` should be used.

Allow delete script to be run without the MySQL PROCESS privilege.

---

tools/delete_imaging_upload.pl

Script `delete_imaging_upload.pl` takes an unusually long amount of time to complete when the number of entries in table `parameter_file` is large. This PR optimizes the query used to determine the rows to delete from table `parameter_file` so that running time is acceptable. Execution time going from an hour to a second were observed with this improvement!

Optimization of the delete imaging upload script.

---

python/lib/utilities.py

when a byte-order mark (BOM) is present, the script fails (participant_id is not found in participants.tsv) since the field extracted is \ufeffparticipant_id (happened on 2 different instances).
Modifying the tsv parser to add an encoding parameter fixed the issue.
```
> print(row)
OrderedDict([('\ufeffparticipant_id', 'sub-OTT174'), ('age', 'n/a'), ('sex', 'n/a'), ('hand', 'n/a')])
```
```
Traceback (most recent call last):
File "bids_import.py", line 454, in <module>
main()
File "bids_import.py", line 75, in main
read_and_insert_bids(bids_dir, config_file, verbose, createcand, createvisit)
File "bids_import.py", line 158, in read_and_insert_bids
bids_reader = BidsReader(bids_dir, verbose)
File "/data/loris-mri/bin/mri/python/lib/bidsreader.py", line 62, in __init__ …
```

Encoding issue

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

ANSI-C quoting (e.g. $'/t') are not supported on all shells. On Ubuntu, the default shell on /bin/sh (used by default by Perl when running system) is dash and does not support it. Bash does. 
The grep construct, which identifies DICOM files with identical studyUID, seriesUID, echo and seriesDesc in `uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm` uses a ANSI-C quoting tab, and on some system the grep command fails: 0 files matched the pattern despite some match. Forcing perl system to execute the command on bash fixes the issue.

Grep issue

---

docs/05-PipelineLaunchOptions.md

This updates the BIDS import documentation to add details about the structure of the `participants.tsv` file.

Update BIDS import documentation to add details about the participants.tsv file

---

README.md

Corrected 2 typos in the first paragraphs of the README. It said 22.0.* when it should have been 23.0.*
This fixes #632

[docs] Fixed typo in version 23.0 README

---

imaging_install.sh

The DateTime CPAN library was missing from the cpan install commands of the install script. This PR adds it.
Note: this library was added by the PET insertion pipeline

Add missing CPAN library to install

---

README.md

Fixed typo in README. It said 22.0.* when it should have been 24.0*.
This fixes #633.

[docs] Fixed typo in README

---

uploadNeuroDB/NeuroDB/MRI.pm

Modified the Perl pipeline to reflect that the new default value of ScannerID is NULL in the mri_protocol table. This PR should only be merged when [#7496](https://github.com/aces/Loris/pull/7496) is ready to be merged as well.
**Testing instructions**
1. Choose one subject from the RaisinBread dataset to be deleted and re-inserted. The recommended patient is `ROM248` since this patient has not been QC'ed yet and thus the script `delete_imaging_upload.pl`
2. Delete the patient using `delete_imaging_upload.pl`.
3. Run the insertion pipeline and verify that no errors have occurred.

[Perl] Set default ScannerID value to NULL

---

imaging_install.sh

Added a check in `imaging_install.sh` to see if `/data/incoming/` was successfully created. If it was not created, instructions on how to do it manually are provided. This PR address the first task in #498 
Run the `imaging_install.sh` and ensure that it is running smoothly.

Added a check to see if /data/incoming/ was created in imaging_install.sh

---

python/lib/bidsreader.py

This PR improves a little the logs of the error when doing comparison between the list of subjects present in participants.tsv and the list of subjects grepped by the BIDS reader.

Display more elaborate message in the error for comparison of subjects present in participants.tsv and the ones present in the BIDS layout

---

python/bids_import.py
python/lib/utilities.py

This fixes an issue for prospective studies importing BIDS dataset one subject at a time.
Until now, the pipeline always checked that the file content in the bids_import directories matched the file content in the incoming BIDS directory. When loading one subject at a time, this will cause failures as the participants.tsv file would change for each subject loaded. Instead, in this PR we read the content of the participants.tsv file for the new upload and compare it to the participants.tsv file already existing in the bids_import directory. If there are new subjects listed in the new participants.tsv, it will append a row to the participants.tsv file present in the bids_import directory to add the subject to it.

Append entries to participants.tsv if participants.tsv file already exists in bids import

---

python/lib/session.py

Current_stage is not set when creating a visit via the bids_import.py pipeline which causes the frontend to crash when trying to load the candidate page in access profile.
```
PHP Fatal error:  Uncaught TypeError: Return value of Utility::getStageUsingCandID() must be of the type string, null returned in /var/www
> /loris/php/libraries/Utility.class.inc:632\nStack trace:\n#0 /var/www/loris/modules/instrument_list/php/instrument_list.class.inc(177): Utility::getStageUsingCandID('207019')\n#1 /var/www/loris/php/libraries/NDB_Page.class.inc(
> 707): LORIS\\instrument_list\\Instrument_List->setup()\n#2 /var/www/loris/src/Middleware/UserPageDecorationMiddleware.php(234): NDB_Page->handle(Object(Laminas\\Diactoros\\ServerRequest))\n#3 /var/www/loris/src/Middleware/PageD
> …
```

Add Current stage when creating the visit for the bids_import.py pipeline

---

imaging_install.sh

In an effort to make `imaging_install.sh` more error-proof, a new check is added to ensure that the connection to the database is valid. If the user provides invalid credentials (username and/or password), then the script will alert them and abort. For any other connection problems, the MySQL error message is printed out instead. This address the second task in #498. 
1. Run the `imaging_install.sh` script with incorrect username and password a check that the script catches the error and exits. The error printed out should be:
`ERROR: invalid username and/or password. Aborting...`
2. Run the script again with other incorrect credentials (i.e host, database name, etc.) and see if the script catches those errors as well.
3. Run the script with correct credentials to ensure that everything …

Add database connection check in imaging_install.sh

---

imaging_install.sh

Improved distribution detection by adding support for all Debian-based (Ubuntu, Debian) and RedHat-based (RedHat, CentOS, Fedora, Oracle) distributions. This PR addresses the third task in #498. The added code is also based off the code provided in #498. 
1. First, run the following command in the terminal to check that it can properly detect your Linux distribution:
```bash
hostnamectl |awk -F: '/Operating System:/{print $2}'|cut -f2 -d ' '
``` 
2. Next, create a bash script containing only the block of code below. Ensure that if you are running a Debian distribution that DICOM Toolkit automatically installs:
```bash
os_distro=$(hostnamectl |awk -F: '/Operating System:/{print $2}'|cut -f2 -d ' ')
debian=("Debian" "Ubuntu")
redhat=("Red" "CentOS" "Fedora" "Oracle")
if [[ " ${debian[*]} " …
```

Improved distribution detection to imaging_install.sh

---

uploadNeuroDB/minc_insertion.pl

A part of the code in minc_insertion.pl has been duplicated by a rebase done on the HRRT PR. This caused a section of the script to be duplicated. Kept the second instance in the script so that it works for both MRI and HRRT PET data. 
Note: for PET data, there is no `PatientName` in the `$studyInfo` hash as there are no DICOM for HRRT data. Instead, it is getting that information from the MINC header `patient:full_name`, hence why needed to keep the second instance of the duplicated code instead of the first one.

Remove the duplicated section of code due to a bad rebase when rebasing the HRRT PR branch with main

---

python/lib/candidate.py

Adapt the logic from #558 to use project and site Names instead of Alias.
Motivations: 
- readibility
- uniformity (subproject's value is subproject's title)
- follow API's logic where project and site Names are used
Note: In candidate.py, the if self.site case was deleted. To my understanding, it wil lbe populated after the first iter with the first participant's site, and assume that all subsequent participants are from the same site, which is not necessary the case.

Participants.tsv: Use project and site name instead of alias

---

python/bids_import.py
python/lib/bidsreader.py
python/lib/database.py
python/lib/eeg.py
python/lib/physiological.py

The current version of eeg.py handles the import of a single physiology file per subject/modality folder. This extends the current code to import all the physiology files present with their appropriate metadata.
-- note: 
~~The derivative case is broken until I revisit #608 ([code L162-165](https://github.com/aces/Loris-MRI/pull/608/files#diff-250dc8b14f8948bfc4cf003892b0da4257fc45681b3e49d5a7af615e552ea5bbR163) is already commented so it does not break anything).~~
The derivative case is fixed and needs testing.

BIDS import - handle multiple physiology files and derivatives

---

python/lib/database_lib/mriupload.py

Flake8 with mriupload.py

---

python/lib/database_lib/mriscanner.py

Flake8 with mriscanner.py

---

python/mass_nifti_pic.py

Flake8 with mass_nifti_pic.py

---

python/mass_electrophysiology_chunking.py

Flake8 with mass_electrophysiology_chunking.py

---

python/react-series-data-viewer/eeglab_to_chunks.py

Flake8 with eeglab_to_chunks.py

---

python/react-series-data-viewer/edf_to_chunks.py

Flake8 with edf_to_chunks.py

---

python/dicom_archive_validation.py

Flake8 with dicome_archive_validation.py

---

python/lib/bidsreader.py
python/lib/candidate.py

Flake8 with candidate.py

---

python/lib/bidsreader.py

Flake8 on bidsreader.py

---

README.md
docs/02-Install.md
docs/03-TechnicalInfrastructure.md
docs/05-PipelineLaunchOptions.md
imaging_install.sh

All the scripts that were originally found in `/data/$PROJ/bin/mri` are now moved to `/opt/$PROJ/bin/mri`. The README documentation, docs and installation script have been updated accordingly. This addresses #479

Move imaging scripts from /data to /opt

---

dicom-archive/profileTemplate.pl
docs/scripts_md/ConfigOB.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm

Config setting `useProjects` has been removed from the LORIS code base since version 21.0 as projects are always "used" now. This PR removes from the LORIS-MRI codebase any reference or access to that setting.
How to test:
- Ensure setting `useProjects` is not in the DB
- Insert a scan that belongs to a candidate that does not exist in the DB and ensure that the profile file specifies a project ID and a subproject ID for that candidate/visit.
- Test that the scan is inserted successfully and that the candidate is created by the pipeline, along with the appropriate visit.
Fixes #670

Stop using config setting useProjects (projects are always "used" now)

---

.github/workflows/flake8_python_linter.yml
python/requirements.txt

A new Python linter, flake8, has been added as a GitHub Action. It will run on every submitted PR and annotate all the errors that it finds. This PR addresses the issue #649. 
Documentation for the GitHub Action can be found [here](https://github.com/marketplace/actions/run-flake8-with-reviewdog). Essentially, this GitHub Action runs flake8 with [reviewdog](https://github.com/reviewdog/reviewdog). Reviewdog parses the output from flake8 and uses to it annotate code in the PR.

Added a GitHub Action that will run flake8 on submitted PRs

---

python/lib/imaging.py

Flake8 with imaging.py

---

uploadNeuroDB/NeuroDB/MRI.pm

This PR resolved the bug reported in #674
The method `getPSC` was being passed the incorrect variable. 
`$dbhr` is not defined in the scope of the function `getSesisonInformation`, but rather the it is defined as `$dbh`. See [this line](https://github.com/aces/Loris-MRI/blob/121ae9611ff8a7f3d55f295d74011762adae9760/uploadNeuroDB/NeuroDB/MRI.pm#L141)

[Bugfix] call to getPSC was passed wrong variable

---

dicom-archive/profileTemplate.pl
docs/scripts_md/ConfigOB.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm

Config setting `useProjects` has been removed from the LORIS code base since version 21.0 as projects are always "used" now. This PR removes from the LORIS-MRI codebase any reference or access to that setting.
How to test:
- Ensure setting `useProjects` is not in the DB
- Insert a scan that belongs to a candidate that does not exist in the DB and ensure that the profile file specifies a project ID and a subproject ID for that candidate/visit.
- Test that the scan is inserted successfully and that the candidate is created by the pipeline, along with the appropriate visit.
Fixes #670 for release 23.0

 Stop using config setting useProjects (projects are always "used" now) for 23.0 bug fix release

---

python/lib/database_lib/physiologicalannotationarchive.py
python/lib/database_lib/physiologicalannotationfile.py
python/lib/database_lib/physiologicalannotationinstance.py
python/lib/database_lib/physiologicalannotationlabel.py
python/lib/database_lib/physiologicalannotationparameter.py
python/lib/database_lib/physiologicalannotationrel.py
python/lib/eeg.py
python/lib/physiological.py

This PR adds support for derivatives, specifically annotations.
Annotations are added using 2 files, *_annotations.json (metadata) and _annotations.tsv (data), both mandatory.
For a template:  ([tsv](https://github.com/bids-standard/bids-examples/blob/9893043f52ab1cec144d1b6069497ef48edc9570/eeg_face13/derivatives/BIDS-Lossless-EEG/sub-001/eeg/sub-001_task-faceFO_annotations.tsv)) ([json](https://github.com/bids-standard/bids-examples/blob/9893043f52ab1cec144d1b6069497ef48edc9570/eeg_face13/derivatives/BIDS-Lossless-EEG/sub-001/eeg/sub-001_task-faceFO_annotations.json)) 
To test 
The PR depends on an SQL patch from https://github.com/aces/Loris/pull/7345 
PyBIDS won't detect *_annotations.json and _annotations.tsv with validate turned on without the …

EEG-BIDS pipeline - Derivatives support: annotations

---

uploadNeuroDB/register_processed_data.pl

This fixes a bug where the call to the NeuroDB::MRI::findScannerID function had an extra argument causing the following error:
```
Attribute (db) does not pass the type constraint because: Validation failed for 'NeuroDB::Database' with value 0 (not isa NeuroDB::Database) at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Moose/Object.pm line 24
Moose::Object::new('NeuroDB::objectBroker::MriScannerOB', 'db', 0) called at /data/qpn/bin/mri/uploadNeuroDB/NeuroDB/MRI.pm line 969
NeuroDB::MRI::findScannerID('SIEMENS  ', 'TrioTim  ', '35008  ', 'syngo MR B17 ', 1, 'REF(0x490d7b8)', 0, 'NeuroDB::Database=HASH(0x49d6fb0)') called at /data/preventAD/bin/mri/uploadNeuroDB/register_processed_data.pl line 266
Argument "8Exiting now\n\n" isn't numeric in right bitshift (>>) at run_defacing_script.pl line …
```

Fix bug in findScannerID function call in register_processed_data.pl

---

python/lib/imaging.py
python/mass_nifti_pic.py

This fixes a few bugs found when testing mass_nifti_pic.py:
- fixes the warning printed
- checks whether a pic has already been created and is present in parameter_file. If so, print a warning that the pic already exists and that if the user wishes to recreate it, the option `--force`/`-f` should be used when running the script
- adds a force option to force the re-creation of the pic on the filesystem with the same path as the path already stored in the database

Fix mass_nifti_pic.py in the case there is already an entry in parameter_file for the pic path

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

The code in class `uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm` does not compile: variable `$sth` is declared twice (with `my`) in method `CreateMRICandidates`.
Fixes #720

Repair invalid code in uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

---

uploadNeuroDB/imaging_non_minc_insertion.pl

Script uploadNeuroDB/imaging_non_minc_insertion.pl uses code that is no longer supported in earlier versions of Perl. This PR refactors the script so that it works with all Perl versions.
Fixes #721

uploadNeuroDB/imaging_non_minc_insertion.pl now works with all versions of Perl

---

dicom-archive/get_dicom_info.pl
docs/scripts_md/MRI.md
docs/scripts_md/get_dicom_info.md

Some options were still being described for get_dicom_info.pl even though they were removed from the script as noticed in https://github.com/aces/Loris-MRI/issues/710. This updates the different documents accordingly.
Note: mass_perldoc script was used to regenerate the MD files and picked up a documentation change in MRI.pm as well so the MD file of MRI.pm is being updated as well.

Update get dicom info documentation to remove non-existant options

---

tools/delete_imaging_upload.pl

This PR fixes two bugs found while testing the delete script for 24.0 release:
- replace option `-file` by `-basename` in the error and documentation https://github.com/aces/Loris-MRI/issues/724
- fix bug when running the script with `-form` option https://github.com/aces/Loris-MRI/issues/725
Resolves #724 and #725

Fix bugs found when testing the delete script

---

python/lib/physiological.py

When the values for X, Y and Z in the BIDS `*electrodes.tsv` file are set to `n/a`, map those values to `NULL` so that it can be inserted into the `physiological_electrode` table in the DB.
Important note: requires the SQL patch from the following PR https://github.com/aces/Loris/pull/7849

Map n/a values for electrodes X, Y and Z fields to NULL in physiological_electrode table

---

python/lib/scanstsv.py

This PR fixes a NoneType error that gets issued when no entry was found for a given *nii.gz or EEG file in scans.tsv to determine the acquisition date.

Fixes a NoneType error bug when no entry in scans.tsv for a given file and trying to look for an acquisition date

---

dicom-archive/dicomTar.pl

This adds an extra check at the beginning of `dicomTar.pl` to ensure the `-database` option is provided to the script when `-mri_upload_update` is set.
Resolves #732

dicomTar.pl - check that the -database option is provided when -mri_upload_update option is set

---

uploadNeuroDB/minc_insertion.pl

The `determineScannerID` function of the `MRIProcessingUtility.pm` class takes the following arguments:
```
- $tarchiveInfo: archive information hash ref
- $to_log      : whether this step should be logged
- $centerID    : center ID
- $upload_id   : upload ID of the study
```
In minc_insertion.pl, `determineScannerID` is called with the following arguments: `\%studyInfo, 0, $centerID, $NewScanner, $upload_id`
$NewScanner needed to be removed from the function call. Probably the result of a bad conflict resolution...

Remove extra variable from call to determineScannerID function from minc_insertion.pl

---

environment

The LORIS-MRI now gets installed in the `/opt` folder to be moved out of the `/data` mounts so that the scripts and the data are in different directories.
While doing so, we forgot to update the paths in the environment file for the install script. This PR updates the paths to point to /opt instead of /data in the environment template file

Fix the paths in the environment file to be in /opt now that the install script installs LORIS-MRI in /opt

---

python/requirements.txt

The latest version of pybids has a bug where we cannot query the BIDS layout with an `extension` restriction.
So the code here: https://github.com/aces/Loris-MRI/blob/9f2813d45f7e34f0494b6a06f1cd5645cc4d7748/python/lib/eeg.py#L345 does not return any EEG file to insert.
```
eeg_files = self.bids_layout.get(
subject   = self.bids_sub_id,
session   = self.bids_ses_id,
scope     = 'derivatives' if derivatives else 'raw',
suffix    = self.bids_modality,
extension = ['set', 'edf', 'vhdr', 'vmrk', 'eeg', 'bdf']
)
```
=> does not return anything when using pybids 0.14.0. Looks like the `extension` parameter is the culprit here. An issue is being created on the pybids repo to let them know. https://github.com/bids-standard/pybids/issues/800

Require 0.13.2 of pybids in the requirements.txt python packages as 0.14.0 has bugs at the moment

---

docs/scripts_md/delete_imaging_upload.md
tools/delete_imaging_upload.pl

This allows the deletion of files derived from a `FileID` in the `bids_export_files` when there are BIDS files present for the `FileID` to be deleted.
Resolves #723

Add bids_export_files table to the delete script

---

uploadNeuroDB/minc_insertion.pl

The call to `make_pics` from `minc_insertion.pl` is missing the `$db` argument in the function call leading to an error when creating the pic from `minc_insertion.pl`.
Note: this has been fixed on `main` so the fix will be in the next major release as well.

fix the call to make pics from minc_insertion.pl

---

uploadNeuroDB/imaging_non_minc_insertion.pl

This fixes an issue found by a collaborator where the coordinate space provided to the script is not being used when inserting the file into the `files` table.

fix coordinate space not being inserted in the files table when running imaging_non_minc_insertion.pl

---

docs/scripts_md/MRI.md
docs/scripts_md/MRIProcessingUtility.md
tools/cleanup_paths_of_violation_tables.pl
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl

This resolves an issue where when running `minc_insertion.pl` on its own, the files that are inserted into the `mri_protocol_violated_scans`, `mri_violations_log (exclude violations only)` and `MRICandidateError` tables, the file is not moved to `trashbin` and the path inserted in those tables are not reliable as there is no files in the file system.
This is not an issue when running the main pipeline as all the files are moved to `trashbin` at the end of `tarchiveLoader` execution. 
This resolves #739

Move violated files when running minc_insertion.pl

---

docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/MriUploadOB.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/MriUploadOB.pm
uploadNeuroDB/tarchive_validation.pl

While testing 24.0, notice that the `tarchive_validation.pl` script does not verify whether the UploadID provided to the script refers to the same `TarchiveID` as the `ArchiveLocation` provided as an argument. If not, returns an error.
Testing instructions:

Checks that the UploadID and archivelocation provided to tarchive_validation.pl script refers to the same TarchiveID

---

uploadNeuroDB/NeuroDB/objectBroker/TarchiveOB.pm

This fixes a bug where the DICOM archive was not moved anymore in the year subfolder of the `tarchive` folder when run through `tarchiveLoader.pl`. It adds the field `DateAcquired` when querying the `tarchive` table so that the information stored in that field can be used to determine the year subfolder in function `moveAndUpdateTarchive` of `MRIProcessingUtility.pm`.
Note: this bug is not present on 23 releases and specific to 24.
Testing instructions:

Fixes bug where the tarchive is not moved into the year subfolder anymore when running the pipeline

---

uploadNeuroDB/NeuroDB/MRI.pm

This fixes an issue were the NIfTI file generated did not get inserted into the `parameter_file` table.
Resolves #738

minc_insertion.pl - Fix NIfTI file not being registered in parameter_file table

---

python/lib/physiological.py

The `LabelDescription` field of the annotation.json file is optional in BIDS. If a dataset does not have this field in the annotation.json file, then bids_import.py fails with NoneType error.
The proposed fix is to check first if the `LabelDescription` field is set in annotation.json, if so, then insert entries in `physiological_annotation_label` with `label` and `description` present in each entry under `LabelDescription`, otherwise, this step is skipped.

Fix insertion pipeline when there is no LabelDescription in annotation.json (optional field)

---

python/lib/eeg.py

Current behaviour:
Takes one candidate’s annotation files and copies it to all candidates raw sub folders (and also inserts to the DB).
This PR fixes the search by adding the subject as a parameter to the search.

Bugfix - Annotation get_nearest should take subject arg

---

python/lib/physiological.py

```
a = '1.23456'
b = '3'
a.isdecimal()
>> False !! this is problematic
b.isdecimal()
>> True
```
Extend support and make sure that strings in float format are accepted. Otherwise a null is inserted in the onset / duration field of annotation instance

Bugfix: Floats returning false on isdecimal() fxn

---

python/lib/eeg.py
python/lib/mri.py

If the data_dir in the Config module is set without a `/` at the end, then the bids_import pipeline returns error that files are not found on the filesystem due to a missing / between data_dir and the relative path.
In this PR, the string concatenation is replaced by `os.path.join()`, correctly builds the full path to a file by adding a `/` if needed between strings to concatenate.

Use os.path.join to reconstruct directory instead of string concatenation in BIDS import pipeline

---

docs/scripts_md/ConfigOB.md
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm

This PR adds a method to the `ConfigOB` object broker in order to allow the retrieval of config setting `compute_snr_modalities`. It also makes use of this new feature in `MRIProcessingUtilities.pm`. 
Fixes #764 .

Bulletproof the retrieval of the modalities on which to compute the SNR

---

docs/scripts_md/ImagingUpload.md
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/delete_imaging_upload.md
docs/scripts_md/get_dicom_files.md
tools/delete_imaging_upload.pl
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This resolves the following error I was having on my new sandbox when running mysqldump:
```
mysqldump: Couldn't execute 'SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"')                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = 'cecile_raisin_bread' AND TABLE_NAME = 'psc';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109)
```

Turn off column statistics option when running mysqldump

---

python/lib/database_lib/physiologicaleventarchive.py
python/lib/database_lib/physiologicaleventfile.py
python/lib/database_lib/physiologicaleventparameter.py
python/lib/database_lib/physiologicaleventparametercategorylevel.py
python/lib/eeg.py
python/lib/physiological.py
python/lib/utilities.py

This PR refactors how the bids_import handles event files. It adds support for an event.json file in which HED tags can be stored. The PR edits the fetching and inserting of event files and adds an archiving feature similar to the annotation files. 
Please reference this documentation for more info on [HED Tags in BIDS](https://bids-specification.readthedocs.io/en/latest/99-appendices/03-hed.html)
1. The SQL patches from https://github.com/aces/Loris/pull/8036 should be sourced before attempting to test these changes.
2. Place the sample [`*events.json` file](https://github.com/aces/Loris-MRI/files/8209484/task-faceO_events.json.zip) at the root of the RB BIDS directory. 
3. Attempt to test the changes in this PR
4. Try putting the `*events.json` file in a subject directory (and renaming) …

[EEG-BIDS] Add support for events.json file & HED Tags

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py

This adds support to insert images with no acquisition dates available. This is particularly pertinent when it comes to manage data supposed to be shared openly where the dates are considered identifying.
With this fix, the `files` table's `AcquisitionDate` field is set to the date available in the JSON if there is one, otherwise, it is set to `NULL`.

[dcm2bids] Adds support for images that do not have an acquisition date

---

python/lib/database_lib/mri_scanner.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py

This fixes a bug when creating a new entry in `mri_scanner` where the `RegistrationProjectID` of the scanner candidate is missing. This information will be deduced from the `ProjectID` associated to the visit of the imaging session.

[dcm2bids] Get scanner candidate's RegistrationProjectID based on the scanned candidate's visit ProjectID

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py

When a study is run through the whole dcm2bids pipeline, it exits after having run the DICOM validation with message:
```
The DICOM archive validation has failed for UploadID X. Either run the validation again and fix the problem or use --force to force the insertion of the NIfTI file.
```
The correct behaviour is to reload the `mri_upload` dictionary with the latest content for that upload so it reads properly the field `IsTarchiveValidated` and continues processing when that field has been set to 1 in the database.

Reload the mri_upload dictionary before checking if a tarchive has been validated

---

python/lib/scanstsv.py
python/lib/utilities.py

This PR allows to append to `scans.tsv` file if it already exists in the `bids_imports` data directory and a new entry needs to be added.
It also adds support to `n/a` acq_time values if present (this was generated by the BIDS wizard for example)

[bids_import.py] Append to scans.tsv file when it already exists 

---

python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py

This fixes the matching of series descriptions provided in the Config table. Previously, only series description starting with the string provided in the Config table were being excluded, instead of any series description matching the string provided in the Config table.
The check also ignore case when matching.

Fix regex search in python code to exclude series description provided in Config table

---

python/lib/imaging_upload.py

This fixes the return statement of the `create_imaging_upload_dict_from_upload_id` function of `imaging_upload.py` so that if no rows are found for a given UploadID, then None is being returned instead of failing lamentably.

Fix return statement in imaging_upload.py

---

python/lib/database_lib/mri_candidate_errors.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py

This inserts into the MRICandidateErrors table if a NIfTI file has a PatientName that does not correspond to a specific candidate and exits as it is done on the perl side. Otherwise, scans would be inserted anyway to the CandID and it could have attached the scans to a wrong candidate...

[dcm2bids] Insert into MRICandidateErrors if there is a Candidate PatientName mismatch

---

python/lib/database_lib/mri_candidate_errors.py

The table name used in the insert statement to the `MRICandidateErrors` table in the python dcm2bids pipeline failed because the table name appears to be case sensitive on a MariaDB installed on Ubuntu.

Fix case of MRICandidateErrors in the python insert statement that fails on a MariaDB/Linux install

---

dicom-archive/DICOM/DCMSUM.pm

PatientBirthDate should follow a string Value Representation (a.k.a `Date (DA)`) which is of the form `YYYYMMDD`. See [Patient's Birth Date Attribute in DICOM standard Browser](https://dicom.innolitics.com/ciods/rt-dose/patient/00100030) and [descriptions of DICOM value representations](https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html).
Sometimes, some deidentifying tools might insert incorrect date format (latest example was 00/00/0000) which leads to database errors when inserting invalid dates to the `tarchive` table for example.
Proposed fix: if the date is not following the original DICOM Value Representation, then it means a tool was run on it to get rid of the date, therefore, the DICOM scripts will set that date to `NULL` in the `tarchive` table. …

Set DICOM dates to undef if the date does not follow proper DICOM standard

---

docs/scripts_md/MRIProcessingUtility.md
python/lib/database_lib/files.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py
python/lib/mri.py
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/minc_insertion.pl

This PR updates all imaging pipelines to add the PhaseEncodingDirection and EchoNumber information when present in the insertion of new rows into the `files` and `mri_violations_log` tables.
Resolves #784 
Make sure to source the SQL patches attached to https://github.com/aces/Loris/pull/8152 or source the SQL release patch from 24.0.0 to 24.1.0 releases of LORIS.

Add PhaseEncodingDirection and EchoNumber to files and mri_violations_log insert statements

---

docs/scripts_md/MRI.md
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py
uploadNeuroDB/NeuroDB/MRI.pm

This modifies the LORIS-MRI code to use the `PhaseEncodingDirections` and `EchoNumber` fields to determine a scan type. It also updates the code to insert into `mri_protocol_violated_scans` to include the values of those headers.
SQL changes related to this can be found in https://github.com/aces/Loris/pull/8150
- make sure to run the SQL patch submitted in https://github.com/aces/Loris/pull/8150 before upgrading

Add phase encoding direction and echo number to mri protocol and mri protocol violated scans

---

dicom-archive/DICOM/DCMSUM.pm

When FileNumber is set to '' in DICOM header, the dicomTar.pl pipeline crashes when inserting data into the `tarchive_files` table as FileNumber Int column cannot store empty strings. This PR fixes this by setting empty strings to `undef` for that field.

[DICOMSUM] Set FileNumber to undef if it is '' in the DICOM header

---

python/lib/database_lib/mri_scanner.py
python/lib/imaging.py

The default LORIS `get_subject_ids` function in `database_config.py` calls a `get_scanner_candid` function for phantom datasets that was missing from the `imaging.py` library. This PR adds the missing function.

[dcm2bids] Add missing get_scanner_candid function in imaging.py

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py

BIDS requires a `TaskName` field in the JSON files of NIfTI files named with `task-` labels. This PR takes the name after the `task-` character and adds it as a value to the JSON `TaskName` field.

Add TaskName field to JSON side car file for modalities with task-* names

---

python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/imaging.py

`IntendedFor` is a required field that need to be present in fieldmap's BIDS JSON files. This adds the logic to add this field in the BIDS JSON file to avoid BIDS validator failure.
The adopted logic is the most often used in the BIDS community as far as I can tell: 
IntendedFor content = get the list of files acquired after the fieldmap acquisition but before the next fieldmap acquisition.

Add required IntendedFor BIDS field in fieldmap JSON files

---

batch_uploads_tarchive.pl

This fixes the `batch_uploads_tarchive.pl` file so that when the converter is set to `dcm2niix`, the `dcm2bids` python pipeline (`run_dicom_archive_loader.py`) is launched instead of the `dcm2mnc` `tarchiveLoader.pl` script.

Fix batch_uploads_tarchive to redirect to dcm2bids pipeline when dcm2niix is set as a converter in the Configs

---

docs/05-PipelineLaunchOptions.md

This will replace https://github.com/aces/Loris-MRI/pull/805 so that it can go with the next release of LORIS-MRI. I will then send a PR to main to update main with the code of 24.1-release.

Fix markdown typo in 05-PipelineLaunchOptions.md

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_validation_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py

The temporary directories created by the dcm2bids pipeline were not being deleted. This fixes this issue by deleting temporary directories once the pipeline has finished running.

[dcm2bids pipeline] Delete temporary directory created by the pipeline once it is done running

---

python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py

`dcm2niix` is currently hardcoded in the dcm2bids pipeline. Instead of hardcoding it, the pipeline will fetch the value for the `converter` Config setting and use what has been added there. This allows for naming differently the dcm2niix binary to refer to a specific version (for example: `dcm2niix_dev_2a9fbe82`).
Note: this is already the case for `dcm2mnc` so no need to modify the `dcm2mnc` pipeline.

[dcm2bids] Remove hardcoded dcm2niix binary to use the value stored in the `converter` Config setting 

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py

This fixes a few python errors encountered when the session during which the scan has been acquired is not present in the database. Once those are fixed, then proper logging is tracked in the database and the logs (aka: `[ERROR   ] Visit V02 for candidate 627576 does not exist.`)

Fix NoneType errors when the visit of a scanning session does not exist in the database

---

python/lib/imaging.py

Some NIfTI/JSON file do not have some fields available like RepetitionTime, EchoTime etc... This PR fixes the error encountered when no RepetitionTime was found. Instead of failing miserably, it will continue the protocol checks and if no scan type is found for the acquisition, it will be registered in the `mri_protocol_violated_scans` table as expected.

Fix some errors when RepetitionTime is not available in JSON file

---

python/lib/aws_s3.py

This modifies the `upload_file` function of `AwsS3` python class to be able to handle objects starting with `s3://bucket_name/` the same way it is handled by `download_file` function of the same class.

Upload to S3: support object name starting with s3://bucket_name/ for upload

---

python/lib/database.py

The return type document for the `pselect` function of the class `database.py` was wrong in the documentation and this PR fixes the return type of that function

fix database class pselect documentation for the return type

---

python/lib/database_lib/mri_scan_type.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py

The `run_nifti_insertion.pl` pipeline failed when using the option `--scantype` because there was no mapping between a scan type ID and the scan type provided when calling the script. This PR adds this feature.

map scan type to scan type ID when scan type provided to run_nifti_insertion.pl

---

python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py

If a violation file is not found on the filesystem, will skip pushing to S3 bucket since the file is not there because it has either been rerun or inserted which in both cases mean that the file has been moved to either another trashbin directory (if violation persisted during the rerun) or in assembly_bids (if the files has been inserted into the files table). In both case, the new file (violation or inserted) will be picked by the queries and pushed to S3.

[push to S3 script] Skip violation if not found on filesystem since it means the scan has been rerun and moved

---

python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py

This PR adds an if statement to the creation of the list of files to push to S3 so that if the file path stored in the database starts with `s3://`, it will not try to push the file on S3 again.

[Push to S3 script] Skip files already in s3 bucket

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py

After files are pushed to S3, they are removed from the local file system. When that happens and a new session is uploaded to LORIS, the python pipeline will try to determine the run number based on what is present in the filesystem. That is wrong since the previously inserted file for that session are on S3, it does not check the run number there.
Example: 
- session ID 1 has two tarchives: tarchive ID 1 and tarchive ID 2 acquired on two different days. 
- tarchive ID 1 is converted and T1w NIfTI (`sub-1_ses-V1_run-1_T1w.nii.gz`) file is pushed to S3 and remove from local mount/file system
- tarchive ID 2 is converted and new NIfTI created T1w NIfTI file would be renamed `sub-1_ses-V1_run-1_T1w.nii.gz` and then push to S3, overwriting the tarchive ID 1 file on S3...
This PR fixes the …

Fix logic of determining file run number when previously inserted files are already pushed to S3 and not on filesystem anymore

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py

This adds a try/except around the deletion of the temporary processing directory in case the removal of the tmp directory created by the script dcm2bids pipeline encountered a PermissionError. The script will add a warning in the log and notification spool that the temporary directory could not be deleted and will continue execution instead of failing miserably.

[dcm2bids] Fix permission denied issue when trying to erase tmp directory after pipeline is done running

---

python/lib/imaging.py

When an images matches two protocols referring to the same scan type, an error was triggered to say that more than one protocol was matching the parameters of the image even though, the two protocols referred to the same scan type. This fixes this and make sure that the returned list of matching protocols do not contain any scan type duplicatas.

Fix two matching protocols' error when matching protocols are actually the same scan type

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py
python/lib/lorisgetopt.py
python/run_dicom_archive_loader.py
python/run_dicom_archive_validation.py
python/run_nifti_insertion.py
python/run_push_imaging_files_to_s3_pipeline.py

This modifies the run_nifti_insertion pipeline to download S3 files if an S3 URL is provided to the script for option `-n` before running the insertion logic on the file. At the end of the script, if an S3 URL was provided with option `-n`, the script `run_push_to_s3` will be called to push the newly inserted data to S3.
Resolves https://github.com/aces/HBCD-LORIS-MRI-derivatives/issues/39

Add download from S3 and reupload to S3 if file provided to run_nifti_insertion was an S3 URL

---

python/lib/imaging.py

This fixes the following bug occurring when no `acq_time` is available in the image BIDS JSON file:
```
Traceback (most recent call last):\n File "/opt/loris/bin/mri/python/run_dicom_archive_loader.py", line 88, in \n main()\n File "/opt/loris/bin/mri/python/run_dicom_archive_loader.py", line 76, in main\n DicomArchiveLoaderPipeline(loris_getopt_obj, os.path.basename(file[:-3]))\n File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py", line 91, in init\n self._add_intended_for_to_fieldmap_json_files()\n File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py", line 344, in _add_intended_for_to_fieldmap_json_files\n fmap_files_dict = self.imaging_obj.determine_intended_for_field_for_fmap_json_files(self. …
```

fix intended for bug when no acq_time available

---

python/lib/imaging.py

This fixes the following bug occurring when no `acq_time` is available in the image that needs the `IntendedFor` field defined.
```
File "/opt/loris/bin/mri/python/lib/imaging.py", line 1003, in get_list_of_files_sorted_by_acq_time\n    acq_time = self.param_file_db_obj.get_parameter_file_for_file_id_param_type_id(\nTypeError: \'NoneType\' object is not subscriptable\n
```
Related to #861 
Resolves part 2 of https://github.com/aces/HBCD-LORIS-MRI-derivatives/issues/38

fix intended for bug when no acq_time available in files needing intendedFor

---

python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py

When debugging an instance where the `trashbin` content was not being pushed to the S3 bucket while the content of `assembly_bids` and `pic` were being pushed, we noticed that the reason the files were not pushed to S3 was being the config for the LORIS MRI data was missing a `/` at the end and the code was generating the paths to the files in trashbin using `data_dir + violation_file` instead of using the more robust `os.path.join(data_dir, violation_file)`. This PR fixes the issue so that it does not happen anymore if the user forgot the trailing slash in the config module.

fix paths when there are not / at the end of the Config

---

python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py

This fixes the following bug:
"/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py", line 346, in _add_intended_for_to_fieldmap_json_files\n    for key in fmap_files_dict.keys():\nAttributeError: \'NoneType\' object has no attribute \'keys\'

Correct NoneType error in dicom_archive_loader_pipeline.py line 346 when fieldmap dictionary is empty

---

python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py

When running `run_nifti_insertion.py` or `run_push_to_s3.py`, the scripts do not update `Inserting=0` after execution which leads to false lingering 'In Progress' status in the Imaging Upload module.
This PR fixes the logic of update that flag in the database so that the status in Imaging Upload module are correctly set.

Properly update `mri_upload` 'Inserting' column when different sections of the pipeline are run

---

python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/imaging.py

When trying to write the `IntendedFor` field in the JSON file of fmap datasets already pushed to S3, we currently get the following error:
```
Traceback (most recent call last):\n  File "/opt/loris/bin/mri/python/run_dicom_archive_loader.py", line 86, in <module>\n    main()\n  File "/opt/loris/bin/mri/python/run_dicom_archive_loader.py", line 76, in main\n    DicomArchiveLoaderPipeline(loris_getopt_obj, os.path.basename(__file__[:-3]))\n  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py", line 91, in __init__\n    self._add_intended_for_to_fieldmap_json_files()\n  File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py", line 354, in _add_intended_for_to_fieldmap_json_files\n …
```

Add download from S3 for fmap already pushed to S3 that needs to have IntendedFor written in them

---

uploadNeuroDB/NeuroDB/objectBroker/TarchiveOB.pm

Since v24, archive links in the DICOM Archive module are broken.
The regression seems to be linked to this [PR](https://github.com/aces/Loris-MRI/pull/532).
[This query](https://github.com/aces/Loris-MRI/blob/26ca9261ad5c51b26d58f02aee5a4e2007671831/uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm#L459) is migrated [here](https://github.com/aces/Loris-MRI/blob/55d10798422818af5eda850c7d5f0abb5f2e253c/uploadNeuroDB/NeuroDB/objectBroker/TarchiveOB.pm#L73) but without the DicomArchiveID field which is used in the update query [here](https://github.com/aces/Loris-MRI/blob/53ae27ecf5bc0ed0f69a8073ce9e72471e78f81d/uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm#L1688)

DICOM Archive broken archive link fix

---

python/lib/eeg.py
python/lib/utilities.py
python/requirements.txt

This workaround allows MATLAB 7.3 HDF5 files to work with the pipeline despite not being supported by SciPy.
It assumes that the file path fields are already correctly set.
Related to #841 and in testing by NEMAR team, per MCIN-EEG meeting Jan.27
- make sure to install the `mat73` python library using `pip install mat73` after having source the LORIS-MRI `environment` file

MATLAB 7.3 HDF5 Workaround

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py

Resolves the following bug that occurred when setting the scan type option while running `run_nifti_insertion.py`:
```
Traceback (most recent call last):
File "/opt/loris/bin/mri/python/run_nifti_insertion.py", line 126, in <module>
main()
File "/opt/loris/bin/mri/python/run_nifti_insertion.py", line 106, in main
NiftiInsertionPipeline(loris_getopt_obj, os.path.basename(__file__[:-3]))
File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py", line 173, in __init__
self._register_violations_log(self.exclude_violations_list, self.trashbin_nifti_rel_path)
File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py", line 625, in _register_violations_log
'MriProtocolChecksGroupID': self.mri_protocol_group_id …
```

Fix nii insertion mri protocol group id bug

---

python/lib/eeg.py
python/lib/physiological.py

Rebase of #855  (main -> 24.1-release).
Currently, we ignore additional event data from BIDS files.
This PR allows keeping all these additional event data from BIDS import into a new table named `physiological_task_event_opt`.
Issue #835
Note: embeds a try/catch that should be removed when additional events are supported everywhere
Works with but should not require [LORIS 8237](https://github.com/aces/Loris/pull/8237)

keep track of additional event data (24.1)

---

python/lib/database_lib/files.py

This fixes a bug in the query to the `files` table when `EchoNumber` should be used to find a file.

Fix incomplete format bug when querying EchoNumber from files table

---

docs/scripts_md/ConfigOB.md
docs/scripts_md/DBI.md
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/run_defacing_script.md
tools/delete_imaging_upload.pl
tools/minc_to_bids_converter.pl
tools/run_defacing_script.pl
uploadNeuroDB/NeuroDB/DBI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm
uploadNeuroDB/tarchiveLoader.pl

This PR finishes the refactoring of the database config queries to use ConfigOB instead of the DBI library directly.
This resolves #465

Refactor remaining array configs to use ConfigOB instead of the DBI library

---

python/lib/database_lib/mri_candidate_errors.py
python/lib/imaging.py

This PR ensures that no duplicated data are inserted in the `MRICandidateErrors` table using the `SeriesUID`, `EchoTime`, `PatientName` and `Reason` fields.
Related to https://github.com/aces/Loris-MRI/pull/884 and https://github.com/aces/Loris-MRI/issues/890

Add a check before inserting in mri_candidate_errors.py

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py

This fixes the call to the function to get the scan type name when scan type is not provided as an option to the `run_nifti_insertion.py` script.

fix nifti insertion when scan type is not provided

---

python/lib/physiological.py

Change the `TaskName` and `TaskValue` to `PropertyName` and `PropertyValue` for additional event integration to match BIDS naming.
Linked to [LORIS 8432](https://github.com/aces/Loris/pull/8432)

Keep additional events - rename Task to Property

---

python/lib/imaging.py

This fixes a `NameError: name \'image_type\' is not defined` bug introduced by https://github.com/aces/Loris-MRI/pull/891.

Fix `image_type` when inserting into mri_protocol_violated_scans

---

python/lib/database_lib/files.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py

Currently, this fix the querying logic to determine the run number of files by using the `SessionID` instead of the `TarchiveID` to get the list of files already inserted for the session.

Fix run numbering logic to use SessionID and not TarchiveID to figure out the next number of a run

---

docs/scripts_md/MRI.md
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/MriCandidateErrorsOB.md
docs/scripts_md/MriProtocolViolatedScansOB.md
docs/scripts_md/MriViolationsLogOB.md
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
uploadNeuroDB/NeuroDB/objectBroker/MriCandidateErrorsOB.pm
uploadNeuroDB/NeuroDB/objectBroker/MriProtocolViolatedScansOB.pm
uploadNeuroDB/NeuroDB/objectBroker/MriViolationsLogOB.pm
uploadNeuroDB/minc_insertion.pl

When the `tarchiveLoader.pl` script is rerun, it checks whether the file has already been registered into the `files` table before inserting a new entry in the `files` table but the pipeline does not check whether a violation has already been registered into the 3 violation tables (`MRICandidateErrors`, `mri_protocol_violated_scans` and `mri_violations_log`) and inserts duplicates of the same violation as many times as `tarchiveLoader.pl` is run on a DICOM archive.
This was fixed on the python side by https://github.com/aces/Loris-MRI/pull/884 and https://github.com/aces/Loris-MRI/pull/891. This PR fixes this for the Perl side as well using the same algorithm.
Reminder: a unique file entry is now determined by the unique combination of `SeriesUID`, `EchoTime`, `PhaseEncodingDirection` and …

[Perl pipeline] Do not duplicate violation entry if it already exists

---

python/lib/database_lib/physiological_coord_system.py
python/lib/database_lib/point_3d.py
python/lib/eeg.py
python/lib/physiological.py
python/lib/point_3d.py

Note: rebased from #842 to integrate "subproject" to "cohort" naming change
This PR adds a tracking of all coordinate systems related to electrodes from BIDS archives.
Before that, LORIS-MRI only integrated one coordinate system.
Requires a DB update from [Loris Core 8242](https://github.com/aces/Loris/pull/8242).

Keep BIDS multiple electrode coordinate systems

---

.github/workflows/stale.yml

This modifies the GitHub workflow to use 'not_planned' as a reason for auto closing stale issues.

Add default reason 'not_planned' in the GitHub workflow when auto closing stale issues

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py

Run numbers were incorrectly determined when a new tarchive was uploaded. This bug fix will fix the issue.

Get SessionID from the session_obj instead of the tarchive_obj when determining run numbers

---

python/lib/physiological.py

Currently, the relation between physiological files and Electrodes is broken.
This PR fix this missing relation. 
Resolves #907
1. Put a BIDS archive that contains multiple coordinate systems in the incoming folder.
2. Run the BIDS import pipeline.
3. Once done, see if the table `physiological_coord_system_electrode_rel` contains all information needed.

[BIDS import] Relation between Electrodes and physiological files 

---

python/bids_import.py
python/lib/candidate.py
python/lib/eeg.py
python/lib/exitcode.py

- Adds support for the CandID in the participants.tsv's subject_id fields
- Adds support for the CAND_ID/PSCID validation (match) in the folder name if the flag -i is used

candID subject_id support

---

python/lib/bidsreader.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py

Resolves the following bug when running `dicom_archive_validation.py` with an Upload ID that does not exist in the database.
```
Traceback (most recent call last):
File "/opt/loris/bin/mri/python/run_dicom_archive_validation.py", line 75, in <module>
main()
File "/opt/loris/bin/mri/python/run_dicom_archive_validation.py", line 71, in main
DicomValidationPipeline(loris_getopt_obj, os.path.basename(__file__[:-3]))
File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/dicom_validation_pipeline.py", line 29, in __init__
super().__init__(loris_getopt_obj, script_name)
File "/opt/loris/bin/mri/python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py", line 89, in __init__
self.load_imaging_upload_and_tarchive_dictionaries()
File …
```

DICOM archive validation python crashes when run on inexistant upload ID

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py

When `run_dicom_archive_validation.pl` is provided with an UploadID and an ArchiveLocation that do not refer to the same UploadID as the one provided as input to the script, an error will be printed that: `[ERROR   ] UploadID <UPLOAD ID> and ArchiveLocation <TARCHIVE PATH> do not refer to the same upload`.
This failed silently until now.

Return an error when `run_dicom_archive_validation/py` is run on an incorrect UploadID/tarchivePath combination

---

python/run_push_imaging_files_to_s3_pipeline.py

This fixes the handling of options provided to the script `run_push_imaging_files_to_s3_pipeline.py`. The fixes include:
- when no Upload ID is provided to the script, return a message that `--upload_id` is a required option 
- when an Upload ID that does not exist in the database is provided to the script, return a message that the Upload ID does not exist
- remove from the help documentation the `-t` option as it is not a valid option for this script

Fix handling of options provided to the push to S3 script

---

python/lib/aws_s3.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py
python/lib/exitcode.py
python/lib/lorisgetopt.py

Scripts `run_nifti_insertion.py`, `run_push_imaging_files_to_s3_pipeline.py` and `run_dicom_archive_loader.py` crashed miserably when the S3 configuration was not set properly. This PR should properly handle errors related to S3 connections.

Better handle bad configuration of S3

---

tools/petupload_cron_prod

- Create directory if they do not exist
- append time to the file name to avoid conflicts if the script run more than once a day

[petupload_cron_prod] Automatically create dirs

---

python/lib/physiological.py

Checking first for the HED field is necessary because the 'HED' field is optional as per the BIDS specification.

[bids_import] Added check for 'HED' field to prevent KeyError

---

uploadNeuroDB/tarchive_validation.pl

This PR ensures option `-uploadID` is used on the command line when invoking script `uploadNeuro/tarchive_validation.pl`.
Fixes #975

Enforce use of -uploadID in script uploadNeuro/tarchive_validation.pl

---

uploadNeuroDB/bin/deface_minipipe.pl

This should fix the issue @zaliqarosli was having when testing `run_defacing_script.pl`. Use `make_path` from `File::Path` instead of mkdir when creating the output directory for the pipeline.

Change mkdir to make_path in run_defacing_script.pl

---

python/extract_eeg_bids_archive.py
python/lib/aws_s3.py
python/lib/database_lib/mri_scanner.py
python/lib/imaging.py
python/lib/imaging_io.py
python/lib/lorisgetopt.py

This PR requires the mysql patch in LORIS #8685
Test cases:
- With/without upload_id(electrophysiology_uploader): `extract_eeg_bids_archive.py -p <profile> -u <upload_id>`
- With a S3/regular path for EEGUploadIncomingPath
- With/without a value for EEGS3DataPath

[EEG] extract archive script

---

uploadNeuroDB/imaging_non_minc_insertion.pl

This PR modifies script `imaging_non_minc_insertion.pl` so that it displays an error message if the argument to option `-date_acquired` is not a valid date in format `YYYY-MM-DD`.
Fixes #986

[imaging_non_minc_insertion] Validate -date_acquired argument

---

dicom-archive/profileTemplate.pl

This PR adds controls in the profile template for `@db` initialization.
This will raise an error if the `db` variable is not defined or not well initialized.
Linked to [LORIS Core 8666](https://github.com/aces/Loris/issues/8666)

Control DB parameters initialization

---

uploadNeuroDB/register_processed_data.pl

This PR modifies the checks done in script `register_processed_data` so that the project ID is reported missing only if it really is.
Fixes #988

[register_processed_data] Project ID is only reported missing when it really is

---

uploadNeuroDB/imaging_non_minc_insertion.pl

This PR fixes a bug that prevented the log entries for the execution date to be output to the log file when running script `imaging_non_minc_insertion.pl`.
Fixes #983

[imaging_non_minc_insertion] Missing lines in the log file

---

uploadNeuroDB/imaging_non_minc_insertion.pl

This PR removes the following error message obtained when running script `imaging_non_minc_insertion.pl` with an invalid argument to the `-upload_id` option:
```
DBD::mysql::st execute failed: Incorrect integer value: '<whatever_invalid_upload_id>' for column 'ProcessID' at row 1 at /data1/loris/bin/mri/uploadNeuroDB/NeuroDB/Notify.pm line 130.
```
The validation of the upload ID needs to happen **before** calling `NeuroDB::Notify->spool()` as this call requires a valid upload ID

[imaging_non_minc_insertion] Error message obtained when an invalid upload ID is specified on the command lineline

---

docs/04-Scripts.md

This PR adds a precision for delete script so mysqldmp can be executed without error.

[delete_imaging_upload] reload privilege for mysqldump

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

This PR modifies `MRIProcessingUitlies.pm` so that an error message is displayed when the script referred to by config setting `get_dicom_info` is invalid (i.e does not exists or is not executable). This PR affects any script that converts DICOM files into MINC files (the pipeline itself, `tarchiveLoader`, etc...)
Fixes #1011

Improved error message when get_dicom_info.pl does not exist or is not executable

---

docs/scripts_md/get_dicom_files.md
tools/get_dicom_files.pl

This PR validates the `-outdir` argument in script `get_dicom_files.pl`. This prevents the script from crashing when the name of a non-existent or non-writable directory is supplied to `-outdir`. The documentation for option `-outdir` is also improved by this PR.
Fixes #1007

[get_dicom_files.pl] Validate argument supplied to -outdir

---

uploadNeuroDB/NeuroDB/MRI.pm

When trying to run the MRI pipeline on an empty archive, I got this error message:
```
Usage: file [-bcEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type]
[-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
file -C [-m magicfiles]
file [--help]
```
since the pipeline attempts to run `file` on an empty set of files and consequently builds an invalid Unix command in trying to do so. This PR will first check if the list of files on which `file` should be run is empty before attempting to run the command, thereby getting rid of the error message.
Fixes #1012

Error message from file program when the pipeline is run on an empty archive

---

python/lib/aws_s3.py

Implements copy_file that copies a src bucket file/folder to a dest bucket file/folder

[AWS S3] Copy file

---

python/extract_eeg_bids_archive.py
python/lib/aws_s3.py

Fix 
==> tmp_path could not be uploaded to the S3 bucket. Error was /subdir/file processing failure, must be a s3 url.
--> Cause: os.path.join() called on a string with leading / will return that string.
--> Solution: remove the leading string.

Aws upload dir subdir fix

---

python/lib/imaging.py

The changes here are intended to help address two different issues surrounding bids_import and parameter files.  This PR is targeted at the `24.1-release` branch.
- When importing parameter_file values that are a list, do not convert the entire list to a string before join(b8c8e444c883aeff9858986a8329a0af71c0752c).  This ensures that the list is joined correctly instead of creating a list of every character from the original value.
- Check to ensure parameter_file is not empty before attempting to make any changes to int, or float lists(98b0c5fce679aea0d756fd4c2165253ed4354bfe).  This prevents the `bids_import.py` script from failing if a parameter value contains an empty list.

Fixes for parameter file value lists

---

.github/workflows/stale.yml

For some reason, the workflows are not automatically closing the issues with the not planned tag. Trying to fix that with this PR.

Fix possible typo in close-issue-reason for the github workflow

---

.github/workflows/stale.yml

The "not_planned" tag was not working most likely because the workflows were using a much older version of the stale github action. Version has been upgraded from 3 to 9.0.0 and reason for closing an issue removed since the default is supposed to be "not_planned".
@christinerogers let's see if that does the trick!

Upgrade version of action/stale library to use in the github workflow to use the most recent one

---

python/requirements.txt

Same as https://github.com/aces/Loris-MRI/pull/1031 but for 24.1-release branch...

Fix requirements file for 24.1-release

---

python/lib/physiological.py

This fixes a bug in electrode insertion, where more than one electrode was being inserted every time.

[bids_import] Add single electrode value instead of all electrode values

---

python/react-series-data-viewer/chunking.py

This PR resolves the data shift issue mentioned in aces/Loris#8892 by adding the number of valid samples in the last chunk to the index.json.
It has a Loris PR counterpart: aces/Loris#8999 to use this value and address the fact that some calculations were being made by multiplying the number of chunks by the number of values per chunk, assuming they were all full.

[bids_import] Added validSamples to index.json + Self-descriptive renames

---

dicom-archive/DICOM/DCMSUM.pm

This PR fixes a bug that caused column `TarchiveSeriesID` not to be set properly for acquisitions that do not have an echo time.
Fixes #1054

Properly set field TarchiveSeriesID for acquisitions that do not have an echo time

---

uploadNeuroDB/register_processed_data.pl

This fixes the issue where the defacing script fails because of a constraint that was added at the last release that should not have been added as a `SourceFileID` can be listed in the `InputFileIDs` list provided by the script.
Resolve #1096

Remove the extra constraint saying that the SourceFileID should not be in InputFileIDs provided to the script

---

uploadNeuroDB/register_processed_data.pl

In `register_processed_data.pl`, the `subjectIDsRef` used to determine the `ProjectID of the file to register did not populate the `PSCID` field, needed in order to determine the `ProjectID`. This PR fixes this issue.
Resolve #1102

Fix project id error when running register processed data

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py

This fixes the `NoneType` error found when testing `run_dicom_archive_validation.py` on an inexistant `UploadID`.
Close #1094

Fix nonetype error when running `run_dicom_archive_validation.py` on an inexistant UploadID

---

tools/minc_to_bids_converter.pl

This PR fixes the JSON format in the bids-validator-config.json file generated by minc_to_bids_converter.pl.
Before this PR, there was an error when running the bids validator:
After this PR, the bids-validator makes a lot more sense:

[minc_to_bids_converter] Fix json format

---

uploadNeuroDB/minc_insertion.pl

This PR improves the validation done on the command line parameters for script `minc_insertion.pl`. More specifically:
- When the argument to `-upload_id` refers to a non-existent upload, the script displays a message indicating that the upload ID is invalid.
- When the upload ID passed on the command line refers to an upload that does not have an associated `tarchive` (i.e value of `TarchiveID` for that upload is `NULL` in table `mri_upload`), an error message to that effect is displayed to the user.

[minc_insertion] Improve command line arguments validation

---

python/bids_import.py
python/lib/eeg.py

This PR closes #1118 and is related to aces/Loris#9223.
Instances of the string `derivatives`, which break the `bids_imports` pipeline, have been replaced with `derivative`.
May require SQL/RB amendments from the Loris side.

[python] Replaced critical instances of 'derivatives' with 'derivative'

---

.github/workflows/flake8_python_linter.yml
README.md
install/imaging_install.sh

As discussed in https://github.com/aces/Loris-MRI/pull/1117#discussion_r1697285437, I believe we should update our Python installation. This PR does that, with a few other improvements to our Python environment.
The Python version used in this PR is Python 3.11, which is a relatively recent stable Python version and is likely the best target imo:
- 3.9 and 3.12 require to add APT repositories
- 3.10 also works but is less recent
More precisely, I did not reinstall a full LORIS-MRI instance during my testing, but I did test the PR changes on my Ubuntu 22 dev VM and Debian 12, by doing the following :
- Install the specific Python version and its dependencies.
- Create our virtual environment.
- Install our package requirements in the environment.
Another change made in this PR is that it …

Update Python installation

---

python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py

While running `run_dicom_archive_loader`, I got some errors like `[ERRNO: 18] Incorrect link accross file systems something something` and `something something object 'bool' not callable`  (I don't remember exactly I did not write the errors down) that prevented the script from running. The cause of this error is that `shutil.move` was incorrectly called: a boolean was passed as a third parameter whereas an [optional function is expected](https://docs.python.org/3/library/shutil.html#shutil.move). I removed the superfluous argument and the script works as expected.
I'll notice that this error can be caught by typing :eyes:.

Fix `BasePipeline.move_file`

---

python/lib/database_lib/candidate_db.py
python/lib/database_lib/visit_windows.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/exception/determine_subject_exception.py
python/lib/exception/validate_subject_exception.py
python/lib/imaging.py
python/lib/validate_subject_ids.py

Changes extracted from #1144.
Here are the changes:
- Remove function `validate_subject_ids` in `lib/imaging.py` as it was dead code.
- Add a file `lib/validate_subject_ids` to isolate subject IDs validation.
- Add a directory `python/lib/exception` to contain exception classes.
- Add two exceptions `DetermineSubjectException` and `ValidateSubjectException` to handle subject IDs errors, and use these exceptions where dictionary entries were previously used.
- Simplify the PSCID / CandID combination checking by using a simpler SQL query.

Improve Python subject determination and validation error handling

---

dicom-archive/database_config_template.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/mri.py
python/lib/utilities.py
python/mass_nifti_pic.py

Following the finding on Slack by @cmadjar. Add leading `r` for literal regexes I found in the Python code (Ctrl + F `re.search` / `re.match`).

Add leading r for literal regexes

---

python/lib/bidsreader.py

Changes extracted from #1170, which partially address #1177. These are suggested by tooling (Ruff and Pyright) and since I want to include this tooling in CI, here is a PR to apply these changes first (in order to keep every PR minimal and clean !).

Fix lints in `bidsreader.py`

---

test/Dockerfile.test.php8

During the meeting I just noticed that the Python installation in the Dockerfile no longer meets the recommendation in `README.md`. This fixes it.

Update docker Python install

---

python/lib/scanstsv.py
test/pyrightconfig.json

Improve the global type checker by adding rules for a few things that can obviously be checked as errors even without the presence of types (unbound variables, useless type checks, unused expressions...).

Stricter global type checking

---

test/mri.Dockerfile

Merge some easily mergeable steps and remove some unused dependencies in the dockerfile to reduce the number of Docker layers, which should free some space in our GitHub actions cache.
The "variables should be present before their use" warning was already present before. We'll look into removing it once we have actual integration tests running (still waiting on the S3 bucket for that).

Optimize integration Docker image

---

pyproject.toml

Fix a simple typo in the Pytest configuration.
Previously the `pytest` command was ignoring the configuration because of this typo and all tests, including the integration, tests were ran. This is not what we want since integration tests should only be ran in Docker. Now the command `pytest` only runs unit tests (to run integration tests, use `pytest python/tests/integration`).

Fix Pytest unit tests config typo

---

.gitignore
install/INSTALL.Mac.md
python/lib/db/connect.py
python/requirements.txt

While testing #1150, @cmadjar encountered an issue when connecting to the database through SQLAlchemy. I suspect this is because this connection is using a deprecated version of [`mysql-connector`](https://pypi.org/project/mysql-connector/). This dependency was already present in LORIS-MRI before adding SQLAlchemy although it was unused, and I wrongfully used it for the SQLAlchemy connection not knowing the version we had was deprecated (the non-depecrated version is [`mysql-connector-python`](https://pypi.org/project/mysql-connector-python/).).
Solution: Remove the `mysql-connector` dependency and use `mysqlclient` instead, which is the client we use for the non-SQLAlchemy database connection.
P.S. 1: I manually recreated my virtual environment to make sure the dependency was completely …

Remove mysql-connector dependency

---

.github/workflows/integration.yml
test/db.Dockerfile
test/imaging_install_test.sh
test/mri.Dockerfile

This PR improves the database configuration by doing the following:
1. Store the database name, username, and password in a single place in the GitHub action, removing some duplication.
2. Some minor clean ups.
The main goal of this PR was originally to remove the Raisinbread overwrites but we decided to keep them ultimately, so now it is just a bunch of minor clean ups.

Clean up Docker database scripts

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py

The `bids_mapping_dict` attribute in `nifti_insertion_pipeline.py` is unused, and `get_bids_to_minc_terms_mapping` does not mutate its parameters. Hence the attribute and function call can be removed.
The script works by calling `get_bids_to_minc_terms_mapping` later in `imaging.py`.

Remove unused attribute in NIFTI script

---

install/INSTALL.Mac.md
install/imaging_install.sh
test/mri.Dockerfile

I noticed the LORIS-MRI Docker image was no longer building in CI for #1191. After some investigation, it appears to be because of an update in [Module::Pluggable](https://metacpan.org/pod/Module::Pluggable) (the first in 9 years !), which some of our required packages depend on (notably [DateTime](https://metacpan.org/dist/DateTime), but also others I think). This PR fixes the issue by pinning the version of Module::Pluggable to version 5.2.
During the investigation of this PR, I also changed our pipeline to use `cpan` instead of `cpanm`, which seems to be [the recommended package installer by the Perl community](https://www.cpan.org/modules/INSTALL.html). It provides both a much clearer output (no longer literal tens of thousands of lines) and is faster by approximately 5 minutes.

Fix Perl dependencies (& CI)

---

pyproject.toml
python/lib/database_lib/notification.py
python/lib/db/connect.py
python/lib/db/query/notification.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_validation_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py
python/lib/env.py
python/lib/file_system.py
python/lib/imaging_io.py
python/lib/log.py
python/lib/logging.py
python/lib/lorisgetopt.py
python/lib/make_env.py
python/scripts/extract_eeg_bids_archive.py
python/tests/util/database.py

This PR is a rewrite of the logging and I/O modules of LORIS-MRI.
There are several problems with the current logging and I/O architecture of LORIS-MRI:
1. It is fragmented. The core logging class is the `Log` class. The `BasePipeline` and `ImagingIO` classes build on top of `Log` provide better abstractions, with some amount of duplication between those two classes (some scripts simply use `print` but they are not the subject of this PR).
2. The `BasePipeline` class is too coupled with the DCM2BIDS pipeline to be generalized.
3. The `BasePipeline` and `ImagingIO` classes handle both logging and file system operations, which are two different responsibilities.
4. The logging abstractions are verbose, notably because all logging functions require two keyword arguments  `is_error = 'Y' | …

Unify LORIS-MRI logging

---

test/mri.Dockerfile

Finally fix the warnings in the LORIS-MRI Dockerfile by removing uses of undefined environment variables.

Fix Dockerfile warnings

---

pyproject.toml
python/lib/database_lib/session_db.py
python/lib/db/models/notification_spool.py
python/lib/db/queries/site.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/get_subject_session.py
python/lib/session.py
python/lib/validate_subject_info.py

This PR extracts the "get subject session" operation out of `BasePipeline`, with the goal of making it easily reusable by all scripts, including those that do not use `BasePipeline` (new DICOM archive and eventually BIDS import). It also modernizes the database access by using the new SQLAlchemy abstractions.
Is depended on by:
- #1117 (to implement #1044)

Factorize get subject session

---

python/lib/database_lib/project_cohort_rel.py
python/lib/database_lib/site.py
python/lib/db/queries/site.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/session.py

Depends on #1190
Is depended on by #1211
Migrate "get all sites from the database" to the SQLAlchemy abstraction. I'd like to use the same function in the incremental BIDS import. This PR also deprecate a few functions that already have alternatives in the SQLAlchemy abstraction.

Migrate "get all sites from the database" to the SQLAlchemy abstraction

---

python/lib/database_lib/tarchive.py
python/lib/database_lib/tarchive_series.py
python/lib/db/queries/dicom_archive.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_validation_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py
python/lib/dicom_archive.py
python/lib/imaging.py

Migrate `lib.dicom_archive`, `lib.database_lib.tarchive` and `lib.database_lib.tarchive_series` to the new database abstraction.

Migrate DICOM archive files to new database abstraction

---

python/lib/eeg.py

In LORIS 26, the prePackagedDownloadPath is not properly handled for events archive.
This fixes the issue.

[EEG] prePackagedDownloadPath and archive fix

---

python/lib/db/models/file.py

I did not update the SQLAlchemy model in #1139, whooopsie, the integration tests caught that.

Fix SQLAlchemy file model

---

docs/python/Database_abstraction.md
docs/python/Tooling.md

This PR adds the documentation for the LORIS-MRI Python database abstraction and LORIS-MRI Python tooling taken from https://github.com/aces/Loris/pull/9519.

Python database abstraction & tooling documentation

---

python/lib/database_lib/mri_upload_db.py
python/lib/db/connect.py
python/lib/db/models/dicom_archive.py
python/lib/db/models/mri_upload.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_validation_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py
python/lib/imaging_upload.py
python/tests/integration/scripts/test_run_dicom_archive_loader.py

Migrate `ImagingUpload` and `MriUploadDB` to the new database abstraction.
The current input checking is very complex and this should simplify it a little. The previous code seems to sometimes accept or forget to check if the DICOM archive or MRI upload is null in a few specific places, but I do not see how it can work as a whole in these conditions. I therefore assume the DICOM archive and MRI upload must not be null.
The integration test will check if this works broadly, but since this touches the argument validation, I will need to test the pipeline manually with:
* :white_check_mark: Correct DICOM archive path and correct MRI upload ID.
* :white_check_mark: Correct DICOM archive path.
* :white_check_mark: Correct MRI upload ID.
* :white_check_mark: Incorrect DICOM archive path.
* …

Migrate `ImagingUpload` and `MriUploadDB` to the new database abstraction

---

pyproject.toml
python/lib/database_lib/mri_scanner.py
python/lib/db/queries/mri_scanner.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py
python/lib/scanner.py

Builds on top of #1224. This PR migrates `lib.database_lib.mri_scanner` to the new database abstraction, and migrates the existing code that uses it to the new abstraction.
This PR does not migrate the configuration file that still indirectly uses this code, but this can be done in a follow-up PR (or this PR if wanted).

Migrate `mri_scanner` to the new database abstraction

---

python/lib/db/models/cohort.py
python/lib/db/models/config.py
python/lib/db/models/config_setting.py
python/lib/db/models/dicom_archive_series.py
python/lib/db/models/mri_scanner.py
python/lib/db/models/notification_type.py
python/lib/db/models/parameter_file.py
python/lib/db/models/project.py
python/lib/db/models/site.py
python/lib/db/models/visit.py
python/lib/db/models/visit_window.py
python/lib/db/queries/candidate.py
python/lib/db/queries/cohort.py
python/lib/db/queries/config.py
python/lib/db/queries/dicom_archive.py
python/lib/db/queries/mri_upload.py
python/lib/db/queries/notification.py
python/lib/db/queries/project.py
python/lib/db/queries/session.py
python/lib/db/queries/site.py
python/lib/db/queries/visit.py

Extracted a few changes from my other WIP PRs (refactor `get_subject_info` and incremental BIDS importer) here.
List of changes:
* Add ORM models for `cohort` and `visit`.
* Add some common queries of the shape `try_get_x_with_id` and `try_get_x_with_name`.
* Remove some unwanted newlines that Ruff introduced when removing `Optional` imports.
* Add explicit return types for all queries (NGL I liked inferred return type at first, but now I prefer to have them explicit).
* Use (properly formatted) nested function calls instead of an intermediate `query` variable.

More ORM definitions

---

python/tests/integration/scripts/test_run_dicom_archive_loader.py

Just noticed something that I missed during review. We checked `mri_upload.dicom_archive is not None` several times, but we only need to check it once ! The type checker is smart enough to remember that information in the following statements. I also changed a `dicom_archive.session_id` to a `dicom_archive.session` because I like it.
@cmadjar

small test type improvement

---

docs/scripts_md/MriScannerOB.md
tools/get_dicom_files.pl
tools/minc_to_bids_converter.pl
tools/run_defacing_script.pl
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/objectBroker/MriScannerOB.pm
uploadNeuroDB/register_processed_data.pl

This PR updates the LORIS-MRI codebase following these modifications done in LORIS:
- Addition of new column `ID` in table `candidate`
- Modification of all FK constraints on table `candidate`: the FK is now tied to the above column.

Update of the PERL pipeline following the refactor of the foreign keys on table candidate in LORIS

---

python/lib/config.py
python/lib/db/queries/config.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py
python/lib/make_env.py
python/scripts/import_dicom_study.py

Title. Improve the new `lib.config` module that was introduced in #1250, and adopt it for some configurations in the new DICOM study importer and the DICOM to BIDS pipeline.
The goal of this module is to centralize/factorize access to the in-database LORIS configuration, and to to provide robust validation and error reporting if these configuration values are missing or incorrect.

Improve and adopt more the new `lib.config` module

---

python/lib/aws_s3.py
python/lib/dcm2bids_imaging_pipeline_lib/dicom_validation_pipeline.py
python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/eeg.py
python/lib/imaging.py
python/lib/mri.py
python/scripts/bids_import.py

Some other PR created `lib.util.crypto` to have typed hash functions for the DICOM study importer, but these functions were not adopted in the rest of the codebase. This PR adopts them. A small difference is that the new functions raise an exception if the file does not exist, whereas the old ones return `None`, so I had to check whether there was a possibility that the files do not exist while replacing the old function calls.
This reduces the number of depreciation warnings in CI and makes it possible to delete the untyped functions after LORIS-MRI 27.

Finish to adopt `lib.util.crypto`

---

install/requirements/cpanfile

This PR adds `Date::Parse` to the list of libraries in `install/requirements/cpanfile`.
Fixes #1268

Add Date::Parse to the set of required Perl libraries

---

python/lib/db/models/file.py
python/lib/db/models/imaging_file_type.py
python/lib/db/models/mri_violation_log.py
python/lib/db/models/parameter_file.py
python/lib/db/models/parameter_type.py
python/lib/db/queries/candidate.py
python/lib/db/queries/file.py
python/lib/db/queries/imaging_file_type.py
python/lib/db/queries/mri_scan_type.py
python/lib/db/queries/parameter_type.py

Just a sync of the ORM definitions I have on my fork and the main LORIS-MRI repo after #1257. This PR includes a few stylistic changes (whitespaces), a few renamings (0-to-n relations being put in plural form), a relationship fix (due to a bad review of mine :grimacing:), a new model and a few new queries (unused in LORIS-MRI main for now).

Improve ORM definitions

---

python/lib/db/models/file.py
python/lib/db/models/file_parameter.py
python/lib/db/models/parameter_type.py
python/lib/db/queries/file.py
python/tests/integration/scripts/test_run_nifti_insertion.py

Changes:
* Rename `DbFile.file_name` to `DbFile.rel_path`
* Rename `DbParameterFile` to `DbFileParameter`
* Remove some unnecessary `None`-checks and `str()` in tests.

ORM improvements again

---

python/scripts/bids_import.py

Fixes a bug found in v27 testing (no issue opened)
This fixes the path where the root-level events.json gets copied

Fix copy path for root-level events.json

---

python/scripts/ingest_eeg_bids_datasets.py

Fixed bugs found in v27 testing (no issue opened)
This PR fixes the subject ID used, so that it's uniform and works both when derived from CandID and PSCID (failed test with PSCID)
It also changes the `UPDATE  electrophysiology_uploader` query to `SET Status` to values part of its `enum('Not Started','Extracted','Failed Extraction','In Progress','Complete','Failed','Archived')`

Fix ingest_eeg_bids_datasets.py

---

dicom-archive/dicomTar.pl
docs/scripts_md/ConfigOB.md
docs/scripts_md/GetRole.md
docs/scripts_md/MRI.md
docs/scripts_md/MRIProcessingUtility.md
docs/scripts_md/batch_uploads_tarchive.md
docs/scripts_md/delete_imaging_upload.md
docs/scripts_md/get_dicom_files.md
docs/scripts_md/register_processed_data.md
uploadNeuroDB/NeuroDB/ImagingUpload.pm
uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm

Title. Replace the uses of `dicomTar.pl` by `import_dicom_study.py` in the LORIS MRI pipeline. I would prefer to have this merged for LORIS-MRI 27, but if someone has problems with it 28 is ok too.
Succesfully tested on my local LORIS VM.

Adopt new DICOM study importer in the MRI pipeline

---

uploadNeuroDB/NeuroDB/objectBroker/MriViolationsLogOB.pm

This PR updates `MriViolationsLogOB` to take into account the renaming of column `CandID` into `CandidateID` in table `mri_violations_log`.

Update MriViolationsLogOB.pm following the refactor of the CandID references

---

docs/scripts_md/MRI.md
uploadNeuroDB/NeuroDB/MRI.pm
uploadNeuroDB/NeuroDB/objectBroker/MriProtocolViolatedScansOB.pm

This PR fixes code in `MRI.pm` that would make insertions in table `mri_protocol_violated_scans` fail (due to the refactoring of the CandID field in table `candidate`).

Insertion of scans in table mri_protocol_violated_scans fail

---

python/lib/database_lib/session_db.py
python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py

This fixes a current bug in 26.0 where the creation of a session via the python MRI pipeline failed due to incorrect type being provided to a function.
Note: this will be obsolete for 27.0 since that logic has been rewritten in different library.

Fix bug when trying to create a session via the dcm2bids pipeline

---

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm

When one of the protocol checks fails, the MRI pipeline attempts to save a record in table `mri_violations_log` but an error message is printed saying that column `CandID` does not exist (the dreaded candidate ID refactoring...) This PR updates the MySQL insertion statement so that it uses `CandidateID` instead of `CandID` when inserting in `mri_violations_log`.

Fix insertions in table mri_violations_log

---

uploadNeuroDB/minc_insertion.pl

Currently, there are a few bugs preventing from inserting a MINC file in the database without DICOMs. This PR resolves most of them.

Fix various little bugs preventing the insertion of a MINC file without DICOMs

---

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
python/lib/imaging.py

Replace incorrect uses of `re.match` (which only matches regexs at the beginning of a string) with `re.search`, as per what was found with #1292.

Fix incorrect uses of `re.match`

---

install/requirements/requirements.txt

boto3 introduced a breaking change in their 1.36 release. No time for now to work on fixing this so blocking the version of boto3 to 1.35.99, last working version of boto3 with our current code.
A bug fix will be issued later on so that our pipeline works with latest version of boto3 as well.

set boto3 to install version 1.35.99, last version before boto3 breaking change
