imaging_install.sh
=> Revert "Bug fixes and improvements"

uploadNeuroDB/NeuroDB/ImagingUpload.pm, uploadNeuroDB/imaging_upload_file.pl
Included the correct notification_types in the ImagingUpload.pm and imaging_upload_file.pl files
=> Fixed issues with the notification_types

imaging_install_MacOSX.sh
https://github.com/aces/Loris-MRI/issues/81
https://github.com/aces/dicom-archive-tools/pull/22
Adding mkdir line for /data/incoming as in default install script
=> Improving the Mac install script

imaging_install.sh
https://github.com/aces/Loris-MRI/issues/81
https://github.com/aces/dicom-archive-tools/pull/22
=> Improving the install script

uploadNeuroDB/NeuroDB/ImagingUpload.pm, uploadNeuroDB/imaging_upload_file.pl, uploadNeuroDB/tarchive_validation.pl
This pull-request contains:
- bug fixes and cosmetic changes
- Modifies SourceLocation to DecompressedLocation
- Contains a new function called updateMRIUploadTable to update the DecompressedLocation folder.
=> Mri upload fix

uploadNeuroDB/NeuroDB/ImagingUpload.pm, uploadNeuroDB/imaging_upload_file_cronjob.pl
This pull-request checks to see if uploaded scan is a phantom. If so, it will not validate the patient-name (using dicom-header)
=> Imaging uploader phantom option

uploadNeuroDB/minc_insertion.pl
This pull-request replaces the IsValidated by IsTarchiveValidated.
=> Replaced the IsValidated by IsTarchiveValidated

uploadNeuroDB/imaging_upload_file_cronjob.pl
This pull request contains the following bug fixes:
- Changed the column name from SourceLocation to UploadLocation
- Changed !@Settings::db to !defined @Settings::db)
And also made cosmetic changes for the prompt-message.
=> Fixed a bug and did cosmetic changes

uploadNeuroDB/NeuroDB/ImagingUpload.pm, uploadNeuroDB/imaging_upload_file_cronjob.pl
Modified data-extraction method, for example 
$row['TarchiveID']  is modified to $row[1] as it was causing issues.
=> Fixed the issue with the queries

uploadNeuroDB/NeuroDB/ImagingUpload.pm
Modified the ImagingUpload.pm script to fixed the query.
=> Fixed the query

uploadNeuroDB/NeuroDB/MRI.pm, uploadNeuroDB/mass_nii.pl, uploadNeuroDB/minc_insertion.pl
The NIfTI files will be linked to their MINC files using the parameter_file table with ParameterTypeID corresponding the "check_nii_filename". 
ATTENTION!!!
Need to update profileTemplate to add either:
- $no_nii = 0   # if want to use this functionality, or 
- $no_nii = 1   # if do not want to create NIfTI files.
=> Implemented NIfTI conversion in the imaging pipeline.

uploadNeuroDB/NeuroDB/MRI.pm, uploadNeuroDB/registerFile.pl, uploadNeuroDB/register_processed_data.pl
This option was always set to null and is removed from the files table.
Once this is merged, can run SQL patch to remove ClassifyAlgorithm column:
https://github.com/aces/Loris/pull/1208
=> Removed ClassifyAlgorithm from insertion scripts 

find_uploads_tarchive, uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm, uploadNeuroDB/cleanupTarchives.pl, uploadNeuroDB/minc_insertion.pl, uploadNeuroDB/tarchiveLoader, uploadNeuroDB/tarchive_validation.pl
This makes the path to the tarchive relative in the tarchive table. 
Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/5620
Will need:
- to update dicom-archive-tool repository
- to run MakeArchiveLocationRelative.pl to have all ArchiveLocation in the tarchive table relative (in dicom-archive-tool repository).
=> Tarchive path relative

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
Remove LOG statement from the printing
=> Fixed errors messages while printing into the LOG

uploadNeuroDB/NeuroDB/MRI.pm
The variable $time was initialized inside an if statement instead of before this if statement.
=> Fixed a bug that prevailed insertion of functional imaging scans.

uploadNeuroDB/mass_jiv.pl, uploadNeuroDB/mass_pic.pl, uploadNeuroDB/minc_insertion.pl, uploadNeuroDB/registerFile.pl, uploadNeuroDB/register_processed_data.pl, uploadNeuroDB/tarchiveLoader, uploadNeuroDB/tarchive_validation.pl, uploadNeuroDB/undoUpload.pl, uploadNeuroDB/upload
(!@Settings instead of !defined @Settings). Cleans up a bit errors and warnings of the imaging pipeline.
=> Removed deprecated definition of arrays

environment, imaging_install.sh
- Fixes path problems in the environment file when the pipeline is run in auto-launch mode.
- Updates the install script to reflect the changes done in environment.
=> Fixes for the MRI pipeline when run in auto-launch mode.

uploadNeuroDB/NeuroDB/MRI.pm
same as https://github.com/aces/Loris-MRI/pull/124, but PR124 made it to aces/master instead
=> Resending Tom series description regex from PR124 to 16p0 branch

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm, uploadNeuroDB/tarchiveLoader
Added SNR() to compute the SNR on imaging modalitieas as defined in the prod file.
To be used in conjunction with the following pull requests:
https://github.com/aces/Loris/pull/1993
and
https://github.com/aces/dicom-archive-tools/pull/37
=> SNR computation

uploadNeuroDB/NeuroDB/ImagingUpload.pm
This reflect the changes to the imaging uploader to allow extra text after visit label.
=> Allows Dicom PatientName to have extra text after the visit label

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm, uploadNeuroDB/minc_insertion.pl
Explains what is happening when errors happens
=> better error messages to help find why scans do not go in

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm, uploadNeuroDB/minc_insertion.pl, uploadNeuroDB/tarchiveLoader
Could go in 17.0 or 17.1 when it gets updated.
=> set caveat if acquisitionProtocol is overridden, undef seriesuid

uploadNeuroDB/imaging_upload_file.pl
this is what we discussed in the last Imaging meeting; the duplicate function that makes master not synchronized with 17.0;
pull request sent to the master branch
=> The duplicate function on the master branch that needs to be removed to have master, 17.0 and 17.1 in synch

uploadNeuroDB/minc_deletion.pl
=> Fixed minc_deletion for FileID use case

uploadNeuroDB/NeuroDB/ImagingUpload.pm
I did the same on the dicom-archive-tools repo in case users do not use imaging uploader:
https://github.com/aces/dicom-archive-tools/pull/47
=> Removed files starting with . and __MACOSX directory from the uploaded scans: Redmine 11670

README.md
=> [Installation] Updating README with proper dpkg line

README.md
=> [Installation] Fixing more installation errors

uploadNeuroDB/minc_deletion.pl
https://redmine.cbrain.mcgill.ca/issues/12917
=> minc_deletion: handle multi-echo case when updating number_of_mincInserted

uploadNeuroDB/NeuroDB/MRI.pm
@MounaSafiHarab do you think this is fine?
=> [SQL] Fixing MySQL 5.7 group by during visit creation

README.md, imaging_install.sh
… based on the user's answers during the installation process: Redmine 13199.
Bug pointed out by @christinerogers.
=> New installs now also have their Imaging Pipeline ConfigSettings populated

uploadNeuroDB/NeuroDB/MRI.pm
In MRI.pm, there was some code that used to test for the equality of float numbers using the == operator. This has been replaced by code that first formats the float numbers to 4 decimal places and compares them instead.
Reference [https://docstore.mik.ua/orelly/perl4/cook/ch02_04.htm](url)
=> Corrected code that tests if two float numbers are equal

dicom-archive/dicomTar.pl, docs/scripts_md/dicomTar.md
`pod2markdown dicom-archive/dicomTar.pl > docs/scripts_md/dicomTar.md`
User can type:
perldoc dicom-archive/dicomTar.pl 
=> [Documentation] dicomTar.pl

docs/scripts_md/PodToConfig.md, tools/ProdToConfig.pl
pod2markdown tools/ProdToConfig.pl docs/scripts_md/PodToConfig.md
User can type:
perldoc tools/ProdToConfig.pl 
=> [Documentation] ProdToConfig.pl

docs/scripts_md/seriesuid2fileid.md, tools/seriesuid2fileid
pod2markdown tools/seriesuid2fileid docs/scripts_md/tools/seriesuid2fileid.md
User can type:
perldoc tools/tools/seriesuid2fileid
=> [Documentation] seriesuid2fileid

docs/scripts_md/mincpik.md, uploadNeuroDB/bin/mincpik
Added Perl documentation to `mincpik` along with markdown file associated to this documentation.
=> [Documentation] mincpik

dicom-archive/updateMRI_Upload.pl, docs/scripts_md/updateMRI_Upload.md
Added perldoc for script `updateMRI_upload.pl`. Also ran `pod2markdown updateMRI_upload.pl` to generate `updateMRI_upload.md`, the web-based documentation for the script.
=> [Documentation] updateMRI_upload.pl

docs/scripts_md/concat_mri.md, uploadNeuroDB/bin/concat_mri.pl
As the title says, added perldoc and markdown file for `concat_mri.pl`.
=> [Documentation] concat_mri.pl

README.md
=> README has also within it LORIS-MRI version number, so update

docs/02-Install.md
Based on @MounaSafiHarab's feedback from PR #219, modified the pipeline flow section to mention the extra file checks performed when determining the MRI protocol.
=> [Documentation] Mention the extra file checks in the pipeline flow description

tools/BackPopulateSNRAndAcquisitionOrder.pl, tools/ProdToConfig.pl, tools/example_scripts/deletemincsqlwrapper.pl
- BackPopulateSNRAndAcquisitionOrder.pl
- ProdToConfig.pl
- example_scripts/deletemincsqlwrapper.pl
- no exits are present in seriesuid2fileid
Link to redmine ticket: https://redmine.cbrain.mcgill.ca/issues/14055
=> Implemented the exit code in the tools scripts

dicom-archive/updateMRI_Upload.pl
=> Used proper exit code constants in updateMRI_Upload.pl instead of numeric literals.

docs/scripts_md/File.md, uploadNeuroDB/NeuroDB/File.pm
In PR #266 a new function was created to grep the file types from the database and documented directory in File.pm. In this PR, I simply recreated the File.md so that it includes the documentation of this new function.
=> [Documentation update] File.md perldoc update based from PR #266

tools/database_files_update.pl
Gets rid of the final / if it exists in the data_dir path given in the Config module.
Redmine ticket: https://redmine.cbrain.mcgill.ca/issues/14234
=> Fixed a bug in database_files_update.pl. 

docs/scripts_md/MRIProcessingUtility.md, uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm, uploadNeuroDB/tarchiveLoader, uploadNeuroDB/tarchive_validation.pl
Also noticed that a variable was not used anymore in a function so I removed it from the function and the calls to the function.
=> Fixed the perldoc for MRIProcessingUtility following PR #275

docs/02-Install.md
Documentation up to date with changes on the LORIS side as referenced below:
https://github.com/aces/Loris/pull/3698/files for Deep QC
https://github.com/aces/Loris/pull/3568/files for if_site removal
=> Config table (section 2) documentation updates based on latest 20.0 release status

dicom-archive/updateMRI_Upload.pl, docs/scripts_md/ConfigOB.md, docs/scripts_md/Database.md, docs/scripts_md/DatabaseException.md, docs/scripts_md/MRI.md, docs/scripts_md/MRIProcessingUtility.md, docs/scripts_md/MriScanTypeOB.md, docs/scripts_md/MriUploadOB.md, docs/scripts_md/ObjectBrokerException.md, docs/scripts_md/TarchiveOB.md, docs/scripts_md/UnexpectedValueException.md, docs/scripts_md/updateMRI_Upload.md, uploadNeuroDB/NeuroDB/Database.pm, uploadNeuroDB/NeuroDB/DatabaseException.pm, uploadNeuroDB/NeuroDB/MRI.pm, uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm, uploadNeuroDB/NeuroDB/UnexpectedValueException.pm, uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm, uploadNeuroDB/NeuroDB/objectBroker/MriScanTypeOB.pm, uploadNeuroDB/NeuroDB/objectBroker/MriUploadOB.pm, uploadNeuroDB/NeuroDB/objectBroker/ObjectBrokerException.pm, uploadNeuroDB/NeuroDB/objectBroker/TarchiveOB.pm
This PR corrects the documentation errors found when merging minor into major and also adds the markdown files for the new database framework.
=> Update Perl doc for new database framework

dicom-archive/get_dicom_info.pl, uploadNeuroDB/NeuroDB/ImagingUpload.pm, uploadNeuroDB/minc_insertion.pl
As the title says. Also corrected minor warnings that I was getting when running the pipeline.
=> Added warnings for all files in an archive that are not DICOM images.

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
This PR adds a check when validating that the candidate information from an image have their PSCID and CandID matching.
Because of the missing check between CandID and PSCID in the image, it is possible that MINC files are not associated to the correct candidate. We are working on an MRI doctor script that will do all sort of data integrity checks and this will definitely be one of them. (see #400 for details)
=> Added a check to verify if CandID and PSCID from the image are referring to the same subject

uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
Again, another error inserted by bad conflict resolution between minor and major...
=> Add extension back to Mincinfo_wrapper.pl call

python/bids_import.py, python/lib/candidate.py
=> Revert "[BIDS EEG import] Changed the field CenterID to be RegistrationCenterID when querying the candidate table"

python/bids_import.py, python/lib/candidate.py
=> Revert "Revert "[BIDS EEG import] Changed the field CenterID to be RegistrationCenterID when querying the candidate table""

README.md, batch_uploads_imageuploader.pl, batch_uploads_tarchive.pl, dicom-archive/profileTemplate.pl, docs/01-Introduction.md, docs/02-Install.md, docs/scripts_md/ConfigOB.md, docs/scripts_md/MRI.md, docs/scripts_md/MRIProcessingUtility.md, imaging_install.sh, imaging_install_MacOSX.sh, python/bids_import.py, python/lib/bidsreader.py, python/lib/imaging.py, python/lib/mri.py, python/lib/scanstsv.py, tools/batch_run_defacing_script.pl, tools/batch_run_pipeline_qc_face_script.pl, tools/create_nifti_bval_bvec.pl, uploadNeuroDB/NeuroDB/MRI.pm, uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm, uploadNeuroDB/NeuroDB/objectBroker/ConfigOB.pm, uploadNeuroDB/imaging_non_minc_insertion.pl, uploadNeuroDB/mass_pic.pl, uploadNeuroDB/minc_insertion.pl, uploadNeuroDB/register_processed_data.pl, uploadNeuroDB/tarchiveLoader.pl, uploadNeuroDB/tarchive_validation.pl
This pulls minor into the major branch
=> Pull minor to major for 22 release

INSTALL.Mac.md
Updates to the README Mac install that includes the new perl and python dependencies.
=> Updates to the Mac install README

python/lib/database.py, python/lib/imaging.py, python/mass_nifti_pic.py
This adds a `mass_nifti_pic.py` script to allow mass creation of NIfTI files pic rendering stored in the `files` table.
Insert a `.nii.gz` file into the `files` table and run `mass_nifti_pic.py` on the `FileID` associated to that file. 
Note: make sure you have all python dependencies install (check the install script for the list of `pip` packages that are required by LORIS-MRI)
```
python mass_nifti_pic.py -p database_config.py -s 10000 -l 10000 -v
```
=> [python] Addition of a mass NIfTI pic creation script

docs/scripts_md/MRI.md, uploadNeuroDB/NeuroDB/MRI.pm, uploadNeuroDB/imaging_non_minc_insertion.pl
requiresStaging was removed from the backend pipeline but somehow, two instances remained in the code. This PR cleans that up and completely removes it from the codebase.
=> Removed leftover occurrences of requiresStaging 

tools/delete_imaging_upload.pl
delete_mri_upload.pl -> delete_imaging_upload.pl
=> Script name in instructions was updated

python/lib/eeg.py, python/lib/scanstsv.py
Small typos corrected in order to successfully run the pipeline (IEEG) on a  fresh CentOS install.
=> IEEG modifications typos fix

docs/scripts_md/get_dicom_files.md, tools/get_dicom_files.pl
=> Correct typos in get_dicom_files.pl script doc.

dicom-archive/DICOM/DCMSUM.pm, python/lib/imaging.py, python/lib/mri.py, python/lib/physiological.py
This pulls the code of 22.0-release into 23.0-release now that two bug fixes have been released on 22.
=> Pull 22 into 23

dicom-archive/DICOM/DCMSUM.pm, dicom-archive/dicomTar.pl, python/lib/imaging.py, python/lib/mri.py, python/lib/physiological.py, uploadNeuroDB/NeuroDB/ImagingUpload.pm
This pulls the bug fix releases of 22 and 23 into main.
=> Pull 23 into main

python/react-series-data-viewer/chunking.py
For huge edf files (problem observed for a 8GB file), the chunking script needs to allocate 30GB of memory and fails.
This is because the reader (parsed.get_data) loads all the data points at once. Loading the data points per channel helps to avoid a memory exhaustion error.
=> Chunking script memory optimization

python/react-series-data-viewer/chunking.py
A print statement was left by accident in #605
=> Remove unnecessary print

python/lib/scanstsv.py
=> Flake8 on scanstsv.py

python/lib/mri.py
=> Flake8 with mri.py

python/lib/database.py
=> Flake8 with database.py

python/react-series-data-viewer/chunking.py
=> Flake8 with chunking.py

python/bids_import.py
=> Flake8 with bids_import.py

python/lib/session.py
=> Flake8 with session.py

python/lib/database_lib/tarchive.py
=> Flake8 with tarchive.py

uploadNeuroDB/imaging_non_minc_insertion.pl
This pulls the following fix committed to main that needs to be pulled back into 23.0-release: https://github.com/aces/Loris-MRI/commit/7d2d95c0b37923f2d5039568be20833397702e5c#diff-f2d66efa69a00f3c340fbbce939d7da076e6e626071bac84fcb8d710ddd58df7
=> Pull fix Nicolas made for imaging_non_minc_insertion.pl on main onto 23.0-release

README.md, imaging_install.sh, python/requirements.txt
This fixes the installation process of the python packages. This was tested on the test-install.loris.ca VM.
=> Fix python installation process

python/lib/imaging.py, python/mass_nifti_pic.py
This fixes:
- string/int concatenation bug present in the mass_nifti_pic.py file.
- update or insert values into parameter_file depending on whether they are already present or not
- fix the largest number provided to the script that was not being processed
=> Fix bug where string concatenate with int in mass_nifti_pic.py

python/lib/eeg.py, python/lib/utilities.py
This fixes a few minor bugs for the import of BIDS EEG datasets with SET files but no side FDT files.
=> A few bug fixes for SET and FDT files

docs/scripts_md/ImagingUpload.md, docs/scripts_md/MRIProcessingUtility.md, docs/scripts_md/delete_imaging_upload.md, docs/scripts_md/get_dicom_files.md, python/lib/dcm2bids_imaging_pipeline_lib/dicom_archive_loader_pipeline.py, python/lib/imaging.py, tools/delete_imaging_upload.pl, uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
This adds support to insert images with no series description available. In that case, the actual image parameters will be needed to determine which MRI protocol to use to identify the image.
=> [dcm2bids] Add support for images that do not have a series description

docs/scripts_md/ImagingUpload.md, docs/scripts_md/MRIProcessingUtility.md, docs/scripts_md/delete_imaging_upload.md, docs/scripts_md/get_dicom_files.md, python/lib/database_lib/mri_scanner.py, python/lib/dcm2bids_imaging_pipeline_lib/base_pipeline.py, python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py, python/lib/imaging.py, tools/delete_imaging_upload.pl, uploadNeuroDB/NeuroDB/MRIProcessingUtility.pm
This pulls the latest version of 24.0-release branch into the main branch.
=> Pull 24.0-release branch on main

imaging_install.sh
Fix a string that was not closed properly and made the script buggy at the end of the execution.
=> Fix imaging_install.sh

imaging_install.sh, uploadNeuroDB/NeuroDB/ImagingUpload.pm
- add files to be ignored to pass Candidate validation
- replace dashes by underscores in filenames to pass candidate validation.
=> Installation and pet fixes

uploadNeuroDB/NeuroDB/ImagingUpload.pm
This pulls the latest bug fix release of 24.0.3 into 24.1-release branch.
=> Pull 24.0.3 in 24.1 release

python/lib/aws_s3.py
Adds the capability to download files from S3 bucket. Currently, the `AwsS3` package was just able to upload a file to an s3 bucket or check if a file is already present in the Bucket.
=> Add capability to download file from s3

python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py
This is a tiny bug fix for #833
=> [push to s3 script] Fix violation file paths when checking if the files are on the filesystem before adding them to the list of files to push to S3

python/lib/database_lib/files.py, python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
This fixes the database query to the files table when checking whether a file is already registered in the DB or not.
=> Fix database query to the files table when it checks if file already inserted in DB

python/lib/dcm2bids_imaging_pipeline_lib/nifti_insertion_pipeline.py
This removes some extra debug prints that were committed in a previous PR in nifti_insertion_pipeline.py file.
=> remove prints in nifti_insertion_pipeline.py

python/lib/exitcode.py
This PR adds some of the missing exit code on the python side compared to the perl exit codes list.
=> Add missing exit codes on the python's side

python/lib/imaging.py
This modifies the regex search to ignore case when looking for series description regex in the python imaging pipeline.
=> Ignore case when checking regex for series description in python pipeline

python/lib/aws_s3.py
This add a new function in the `aws_s3` class to be able to delete an object from an S3 bucket. Note: this functionality is needed in order to rename files on S3 buckets.
=> Add a delete_file function for S3 buckets

python/lib/eeg.py
The .set file must be copied before updating the file paths
=> [bids_import] Revised .set insertion logic

python/react-series-data-viewer/chunking.py, python/react-series-data-viewer/edf_to_chunks.py
=> Chunking - add _get_info missing parameter

python/lib/database_lib/mri_scanner.py
=> Fix MriScanner::determine_scanner_information description

python/extract_eeg_bids_archive.py
Log errors without exiting for batch mode to run successfully.
=> Eeg extract script fixes

python/lib/dcm2bids_imaging_pipeline_lib/push_imaging_files_to_s3_pipeline.py
Fix the s3_object_name parameter passed to upload_file. It should  be a full s3:// link.
=> S3 pipeline fix

uploadNeuroDB/register_processed_data.pl
This PR adds validation to the `-sourceFileID` and `-inputFileIDs` options of script `register_processed_data.pl`:
1. Validates that the argument for `-sourceFileID` is a file ID that exists in table `files`.
2. Validates that the argument for `-inputFileIDs` is a list of file IDs separated by `;` and that each file ID exists in table `files`.
3. Validates that each file ID contained in the list described above is not equal to the source file ID (see 1).
Fixes #989
=> [register_processed_data] Add more validation for options -sourceFileID and -inputFileIDs

tools/get_dicom_files.pl
This PR adds a control on `-id` parameter in `get_dicom_files.pl`. 
Fixes #954
=> [get_dicom_files] fix -id parameter

python/lib/eeg.py
The fallback logic is no longer necessary due to the addressed changes being reflected on Loris core
=> [eeg.py] Removed fallback logic and changed file path

python/lib/aws_s3.py
Add an optional parameter to delete a file after a copy.
=> [Aws S3] copy_file optional delete

python/extract_eeg_bids_archive.py, python/lib/eeg.py, python/lib/utilities.py, python/react-series-data-viewer/chunking.py
- A few minor changes in the chunks script to fix warnings
- Add the .set path overrides logic to the extract_eeg_bids_archive.py script
- Disable the .set path overrides logic in bids_import.py in --no-copy is set to true.
=> Update set file path override and chunks logic

python/lib/eeg.py
Fix an issue where the script will try to override the set path when the files are already imported.
=> Update set file path override and chunks logic - bugfix

python/bids_import.py
Add support for the -a short option (--nocopy).
=> [Bids import] Missing short option fix

tools/petupload_cron_prod
Few fixes to petupload_cron_prod following QA testing.
=> petupload_cron_prod script fixes

python/bids_import.py, python/lib/eeg.py, python/lib/utilities.py
Closes #1108.
This PR fixes a few typos and a function call, to enable it to run.
=> [bids_imports pipeline] Fixed typos preventing run

python/mass_electrophysiology_chunking.py
=> [python/mass_electrophysiology_chunking.py] Fix off-by-one error

environment
Centralize the environment change in 2 variables to facilitate manual editing.
=> environment logic change

python/lib/database_lib/physiological_coord_system.py, python/lib/db/model/dicom_archive_series.py
The latest version of Ruff added some lints regarding deprecated typing features, this PR fixes them.
=> Fix new lints

environment, python/bids_import.py, python/extract_eeg_bids_archive.py, python/ingest_eeg_bids_datasets.py, python/lib/eeg.py, python/lib/physiological.py, tools/delete_physiological_file.py
- Fix various issues with the EEG pipeline
- Introduce a new script [tools/delete_physiological_file.py](https://github.com/aces/Loris-MRI/pull/1212/files#diff-a88658a21ba6151a1f5342a5cdbdaa6a21d42499043c8c614107cd9ceba54b4d) to hnalde deletion of a EEG file and its metadata on the DB and optionally the filesystem.
=> [EEG] v26 bugfixes and delete_physiological_file script

python/lib/env.py
=> Fix new PEP585 Ruff lint

python/lib/eeg.py, python/lib/physiological.py
- Fixes https://github.com/aces/Loris-MRI/issues/917
- remove EEGChunksPath from chunk paths to make them relative
=> Disable chunks with useEEGBrowserVisualizationComponents

python/requirements.txt
=> Improve Python requirements order

python/lib/utilities.py
Title. This is for the Python pipelines (BIDS import and DICOM to BIDS).
=> Fix large file hashing memory consumption

uploadNeuroDB/NeuroDB/ImagingUpload.pm
This PR fixes an incorrect variable declaration in `uploadNeuroDB/NeuroDB/ImagingUpload.pm`.
=> Fix compilation error in uploadNeuroDB/NeuroDB/ImagingUpload.pm

uploadNeuroDB/minc_insertion.pl
Currently, there are a few bugs preventing from inserting a MINC file in the database without DICOMs. This PR resolves most of them.
=> Fix various little bugs preventing the insertion of a MINC file without DICOMs (26 rebase)
